// src/lib/pdf.js — PDF Generator (PDFKit)
// Generates: payslips, tax invoices, calibration certificates, audit trail exports

const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const path   = require('path');
const fs     = require('fs');

const NAVY   = '#1B3A5C';
const GOLD   = '#C8960C';
const GREY   = '#94A3B8';
const DKGREY = '#334155';
const LGREY  = '#E8ECF0';
const GREEN  = '#1E6B3C';
const RED    = '#C00000';

const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads');

// Company identity shown on every PDF. Defaults match the original hardcoded
// values; loadCompany() refreshes them from System Settings (company.*) and
// should be called once before generating a document. It's a shared global
// (company identity is the same for all requests), so caching is safe.
let _company = {
  legal_name: 'QALIBRATED SYSTEMS LIMITED',
  address:    'Birdi Singh Complex, Off Mombasa Road, Nairobi',
  email:      'info@qalibrated.co.ke',
  phone:      '+254 714 999 996',
  kra_pin:    'P000000001K',
};
async function loadCompany() {
  try {
    const c = await require('./settings').getCompany();
    if (c && c.legal_name) _company = { ...c };
  } catch { /* keep defaults */ }
}

// ── HELPERS ───────────────────────────────────────────────────────────────────

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function kes(n) {
  return `Kshs ${Number(n||0).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`;
}

function dateStr(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-KE', { day: '2-digit', month: 'long', year: 'numeric' });
}

function drawHRule(doc, y, color = LGREY) {
  doc.moveTo(50, y).lineTo(545, y).strokeColor(color).lineWidth(0.5).stroke();
}

// Every QSL document carries a QR code in the header (top-right of the navy
// bar) encoding its document/certificate number, so a printed copy can be
// verified or looked up. Generated once per document as a PNG buffer (qrcode
// is promise-based; the buffer is awaited by the caller before any synchronous
// PDFKit drawing begins, since PDFKit itself has no async drawing API).
async function getQrBuffer(text) {
  try {
    return await QRCode.toBuffer(String(text || 'QSL-ERP'), {
      type: 'png', width: 120, margin: 0, color: { dark: '#1B3A5C', light: '#FFFFFF' },
    });
  } catch { return null; }
}

function addHeader(doc, title, subtitle = '', qrBuffer = null) {
  // Navy header bar
  doc.rect(0, 0, 595, 80).fill(NAVY);
  doc.rect(0, 80, 595, 6).fill(GOLD);

  // Company name
  doc.font('Helvetica-Bold').fontSize(18).fillColor(GOLD).text('QSL', 50, 22);
  doc.font('Helvetica').fontSize(8).fillColor('#aabbcc').text(_company.legal_name, 50, 44);
  doc.font('Helvetica').fontSize(7).fillColor('#8899aa').text(`${_company.address}  |  ${_company.email}  |  ${_company.phone}`, 50, 56);

  // Title — width trimmed to leave room for the QR code at the right edge
  const titleWidth = qrBuffer ? 432 : 545;
  doc.font('Helvetica-Bold').fontSize(13).fillColor('#ffffff').text(title, 0, 26, { align: 'right', width: titleWidth });
  if (subtitle) doc.font('Helvetica').fontSize(9).fillColor(GOLD).text(subtitle, 0, 46, { align: 'right', width: titleWidth });

  if (qrBuffer) {
    doc.rect(500, 12, 45, 45).fill('#ffffff');
    doc.image(qrBuffer, 502.5, 14.5, { width: 40, height: 40 });
  }

  doc.moveDown(0.5);
  return 100; // y position after header
}

function addFooter(doc) {
  const bottom = doc.page.height - 50;
  drawHRule(doc, bottom - 10, LGREY);
  doc.font('Helvetica').fontSize(7).fillColor(GREY)
    .text('This document is generated by QSL ERP. For queries: info@qalibrated.co.ke', 50, bottom, { align: 'center', width: 495 });
}

// ── GENERIC BUSINESS DOCUMENT ENGINE ───────────────────────────────────────────
// Single configurable renderer covering the 19 QSL_*_Template document types
// (Finance / Procurement / Stores / BD_CRM / HR). Each call site supplies a
// `kind` (see DOC_TYPES below) plus the record data; layout, two-block header,
// line-item table and signature strip are all driven from DOC_TYPES so adding
// a new document only requires a new config entry, not new drawing code.

const DOC_TYPES = {
  quote:            { title: 'QUOTATION',           folder: 'quotes',       blocks: ['client','validity'],  table: true,  sign: ['Prepared by','Approved by'] },
  debit_note:       { title: 'DEBIT NOTE',           folder: 'debit_notes',  blocks: ['client','ref'],       table: true,  sign: ['Issued by','Approved by'] },
  credit_note:      { title: 'CREDIT NOTE',          folder: 'credit_notes', blocks: ['client','ref'],       table: true,  sign: ['Issued by','Approved by'] },
  statement:        { title: 'STATEMENT OF ACCOUNT', folder: 'statements',   blocks: ['client','period'],    table: true,  sign: [] },
  imprest_form:     { title: 'IMPREST REQUEST',      folder: 'imprest',      blocks: ['requester','purpose'],table: true,  sign: ['Requested by','Approved by'] },
  travel_claim:     { title: 'TRAVEL CLAIM',         folder: 'travel_claims',blocks: ['claimant','trip'],    table: true,  sign: ['Claimant','Approved by'] },
  purchase_req:     { title: 'PURCHASE REQUISITION', folder: 'requisitions', blocks: ['requester','dept'],   table: true,  sign: ['Requested by','Approved by'] },
  purchase_order:   { title: 'PURCHASE ORDER',       folder: 'lpos',         blocks: ['supplier','delivery'],table: true,  sign: ['Issued by','Authorised by'] },
  grn:              { title: 'GOODS RECEIVED NOTE',  folder: 'grns',         blocks: ['supplier','order'],   table: true,  sign: ['Received by','Verified by'] },
  goods_issue:      { title: 'GOODS ISSUE NOTE',     folder: 'gins',         blocks: ['issuedTo','project'], table: true,  sign: ['Issued by','Received by'] },
  stock_transfer:   { title: 'STOCK TRANSFER NOTE',  folder: 'stn',          blocks: ['from','to'],          table: true,  sign: ['Released by','Received by'] },
  stock_take:       { title: 'STOCK TAKE SHEET',     folder: 'stocktake',    blocks: ['location','date'],    table: true,  sign: ['Counted by','Verified by'], maxRowsPerPage: 28 },
  leave_application:{ title: 'LEAVE APPLICATION',    folder: 'leave',        blocks: ['employee','leave'],   table: false, sign: ['Employee','Approved by (Supervisor)'] },
  nda:              { title: 'NON-DISCLOSURE AGREEMENT', folder: 'nda',      blocks: ['party'],              table: false, sign: ['QSL Representative','Counterparty'] },
  lead_capture:     { title: 'LEAD CAPTURE FORM',    folder: 'leads',        blocks: ['lead','source'],      table: false, sign: ['Captured by'] },
  client_visit:     { title: 'CLIENT VISIT REPORT',  folder: 'visit_reports',blocks: ['client','visit'],     table: false, sign: ['Reported by'] },
  contract_cover:   { title: 'CONTRACT COVER SHEET', folder: 'contracts',    blocks: ['client','contract'],  table: false, sign: ['Prepared by','Authorised by'] },
  client_onboarding:{ title: 'CLIENT ONBOARDING',    folder: 'onboarding',   blocks: ['client','account'],   table: false, sign: ['Onboarded by'] },
  client_transfer:  { title: 'CLIENT TRANSFER',      folder: 'transfers',    blocks: ['client','transfer'],  table: false, sign: ['Released by','Received by'] },
  service_request:  { title: 'SERVICE REQUEST FORM',  folder: 'srf',          blocks: ['customer','request'], table: false, sign: ['Applicant','Reviewed by'] },
  job_card:         { title: 'FIELD JOB CARD',        folder: 'job_cards',    blocks: ['client','job'],       table: false, sign: ['Technician','Client Representative'] },
};

function fileSlug(s) { return String(s || 'doc').toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 40); }

/**
 * Render any of the document kinds above.
 * @param {string} kind        key into DOC_TYPES
 * @param {object} data        { docNo, blocks: {label:{Key:Val}}, columns, rows, totals, notes }
 *   data.blocks   – e.g. { 'Supplier': {Name:'...', PIN:'...'}, 'Delivery': {Address:'...'} }
 *   data.columns  – [{label,key,weight,align,format}] (when table:true)
 *   data.rows     – array of row objects (when table:true)
 *   data.totals   – [{label, value}] printed under the table
 *   data.body     – free-text paragraphs for non-tabular docs (array of strings)
 *   data.notes    – footer note string
 */
async function generateBusinessDoc(kind, data = {}) {
  const cfg = DOC_TYPES[kind];
  if (!cfg) throw new Error(`Unknown document kind: ${kind}`);
  const dir  = path.join(UPLOAD_DIR, cfg.folder);
  ensureDir(dir);
  const file = path.join(dir, `${cfg.folder}_${fileSlug(data.docNo)}_${Date.now()}.pdf`);
  const qrBuffer = await getQrBuffer(data.docNo || cfg.folder);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, cfg.title, data.docNo || '', qrBuffer);
    let y = 110;

    // Two-block info section (e.g. Supplier / Delivery, Client / Validity)
    const blockEntries = Object.entries(data.blocks || {});
    if (blockEntries.length) {
      const colW = blockEntries.length > 1 ? 237 : 495;
      blockEntries.slice(0, 2).forEach(([label, fields], i) => {
        const x = 50 + i * (colW + 8);
        doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text(label.toUpperCase(), x, y);
        doc.moveTo(x, y + 12).lineTo(x + colW, y + 12).strokeColor(GOLD).lineWidth(1.2).stroke();
        let fy = y + 18;
        Object.entries(fields || {}).forEach(([k, v]) => {
          doc.font('Helvetica').fontSize(7.5).fillColor(GREY).text(String(k).toUpperCase(), x, fy);
          doc.font('Helvetica-Bold').fontSize(9).fillColor(DKGREY).text(String(v ?? '—'), x, fy + 9);
          fy += 26;
        });
      });
      y += 18 + 26 * Math.max(...blockEntries.slice(0, 2).map(([, f]) => Object.keys(f || {}).length), 1) + 14;
    }

    // Line-item table
    if (cfg.table && Array.isArray(data.columns) && Array.isArray(data.rows)) {
      const usableWidth = 495;
      const totalWeight = data.columns.reduce((s, c) => s + (c.weight || 1), 0);
      let cursorX = 50;
      const colX = [];
      data.columns.forEach(c => { colX.push(cursorX); cursorX += (usableWidth * (c.weight || 1)) / totalWeight; });

      const drawTableHeader = (atY) => {
        doc.rect(50, atY, usableWidth, 20).fill(NAVY);
        data.columns.forEach((c, i) => {
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff')
            .text(c.label, colX[i] + 5, atY + 6, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8, align: c.align || 'left' });
        });
        return atY + 20;
      };

      y = drawTableHeader(y);
      let rowsOnPage = 0;
      const rowH = 18;
      const maxRows = cfg.maxRowsPerPage || Infinity;

      data.rows.forEach((row, i) => {
        if (y > doc.page.height - 160 || rowsOnPage >= maxRows) {
          doc.addPage();
          y = 50;
          y = drawTableHeader(y);
          rowsOnPage = 0;
        }
        if (rowsOnPage % 2 === 0) doc.rect(50, y, usableWidth, rowH).fill('#F8FAFC');
        data.columns.forEach((c, ci) => {
          const val = c.format ? c.format(row[c.key], row) : (row[c.key] ?? '—');
          doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
            .text(String(val), colX[ci] + 5, y + 5, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8, align: c.align || 'left' });
        });
        y += rowH;
        rowsOnPage++;
      });
      y += 6;

      (data.totals || []).forEach(t => {
        doc.rect(50, y, usableWidth, 18).fill(LGREY);
        doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(t.label, 60, y + 4);
        doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(String(t.value), 50, y + 4, { width: usableWidth - 10, align: 'right' });
        y += 18;
      });
      y += 14;
    }

    // Free-text body (non-tabular docs: NDA, leave application, reports, etc.)
    if (!cfg.table && Array.isArray(data.body)) {
      data.body.forEach(p => {
        doc.font('Helvetica').fontSize(9.5).fillColor(DKGREY).text(p, 50, y, { width: 495, align: 'left' });
        y = doc.y + 10;
      });
    }

    if (data.notes) {
      doc.font('Helvetica-Oblique').fontSize(8).fillColor(GREY).text(`Notes: ${data.notes}`, 50, y, { width: 495 });
      y = doc.y + 16;
    }

    // Signature strip
    if (cfg.sign.length) {
      const sigY = Math.max(y + 20, doc.page.height - 140);
      const sigW = 495 / cfg.sign.length;
      cfg.sign.forEach((label, i) => {
        const x = 50 + i * sigW;
        doc.moveTo(x, sigY + 30).lineTo(x + sigW - 20, sigY + 30).strokeColor(DKGREY).lineWidth(0.7).stroke();
        doc.font('Helvetica').fontSize(8).fillColor(GREY).text(label, x, sigY + 34);
      });
    }

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/${cfg.folder}/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── PAYSLIP PDF ───────────────────────────────────────────────────────────────

async function generatePayslip(employee, payslip, period) {
  const dir  = path.join(UPLOAD_DIR, 'payslips');
  ensureDir(dir);
  const file = path.join(dir, `payslip_${employee.emp_no}_${period.replace('-', '_')}.pdf`);
  const qrBuffer = await getQrBuffer(`PAYSLIP-${employee.emp_no}-${period}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'PAYSLIP', period, qrBuffer);
    y = 110;

    // Employee details box
    doc.rect(50, y, 495, 70).fillColor('#F0F4F8').fill();
    doc.rect(50, y, 495, 70).strokeColor(LGREY).lineWidth(0.5).stroke();

    doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text(employee.first_name + ' ' + employee.last_name, 65, y + 12);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`Employee No: ${employee.emp_no}`, 65, y + 26)
      .text(`Department: ${employee.department}`, 65, y + 38)
      .text(`Role: ${employee.role}`, 65, y + 50);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`KRA PIN: ${employee.kra_pin || '—'}`, 310, y + 26)
      .text(`NHIF No: ${employee.nhif_no || '—'}`, 310, y + 38)
      .text(`NSSF No: ${employee.nssf_no || '—'}`, 310, y + 50)
      .text(`Pay Date: ${dateStr(new Date())}`, 310, y + 62 - 12);

    y += 85;

    // Earnings section
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text('EARNINGS', 65, y + 5);
    y += 18;

    const earnings = [
      ['Basic Salary', payslip.basic_salary],
      ['Allowances', payslip.allowances || 0],
    ];
    earnings.forEach(([label, amount], i) => {
      if (i % 2 === 0) doc.rect(50, y, 495, 18).fillColor('#F8FAFC').fill();
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
        .text(label, 65, y + 5)
        .text(kes(amount), 0, y + 5, { align: 'right', width: 540 });
      y += 18;
    });

    // Gross
    doc.rect(50, y, 495, 22).fillColor('#E8F5E9').fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GREEN)
      .text('GROSS PAY', 65, y + 6)
      .text(kes(payslip.gross_pay), 0, y + 6, { align: 'right', width: 540 });
    y += 28;

    // Deductions
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text('STATUTORY DEDUCTIONS', 65, y + 5);
    y += 18;

    const deductions = [
      ['PAYE (Income Tax)', payslip.paye, 'KRA — computed on progressive bands'],
      ['NHIF / SHIF', payslip.nhif, '2.75% of gross — NHIF/SHIF'],
      ['NSSF (Tier I + II)', payslip.nssf, '6% on Tier I (≤7,000) + 6% on Tier II (≤36,000)'],
      ['Affordable Housing Levy', payslip.housing_levy, '1.5% of gross (Finance Act 2023)'],
    ];
    if (payslip.imprest_deductions > 0) deductions.push(['Imprest Recovery', payslip.imprest_deductions, 'Outstanding imprest advance recovery']);
    if (payslip.other_deductions > 0)   deductions.push(['Other Deductions', payslip.other_deductions, '']);

    deductions.forEach(([label, amount, note], i) => {
      if (i % 2 === 0) doc.rect(50, y, 495, 22).fillColor('#FFF8F8').fill();
      doc.font('Helvetica-Bold').fontSize(9).fillColor(RED).text(`(${kes(amount)})`, 0, y + 5, { align: 'right', width: 540 });
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY).text(label, 65, y + 5);
      if (note) doc.font('Helvetica').fontSize(7).fillColor(GREY).text(note, 65, y + 15);
      y += (note ? 24 : 18);
    });

    // Total deductions
    const totalDed = payslip.total_deductions || (payslip.paye + payslip.nhif + payslip.nssf + payslip.housing_levy + (payslip.imprest_deductions||0) + (payslip.other_deductions||0));
    doc.rect(50, y, 495, 20).fillColor('#FEE2E2').fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor(RED)
      .text('TOTAL DEDUCTIONS', 65, y + 6)
      .text(`(${kes(totalDed)})`, 0, y + 6, { align: 'right', width: 540 });
    y += 26;

    // Net pay — big box
    doc.rect(50, y, 495, 40).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text('NET PAY', 65, y + 14);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text(kes(payslip.net_pay), 0, y + 14, { align: 'right', width: 540 });
    y += 50;

    // Employer contributions note
    doc.rect(50, y, 495, 50).fillColor('#F0F4F8').fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('EMPLOYER CONTRIBUTIONS (not deducted from salary)', 65, y + 8);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`NSSF Employer:  ${kes(payslip.employer_nssf || payslip.nssf)}`, 65, y + 22)
      .text(`Housing Levy Employer:  ${kes(payslip.employer_housing || payslip.housing_levy)}`, 250, y + 22);
    y += 60;

    // Digital signature notice
    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text('This payslip is digitally signed and verified by QSL ERP (ARCH-007B). For disputes contact HR within 5 working days of receipt.', 50, y, { width: 495, align: 'center' });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/payslips/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── TAX INVOICE PDF ───────────────────────────────────────────────────────────

async function generateInvoice(invoice, client, lines) {
  const dir  = path.join(UPLOAD_DIR, 'invoices');
  ensureDir(dir);
  const file = path.join(dir, `invoice_${invoice.invoice_no.replace(/\//g,'_')}.pdf`);
  const qrBuffer = await getQrBuffer(invoice.invoice_no);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'TAX INVOICE', invoice.invoice_no, qrBuffer);
    y = 110;

    // Invoice meta + client info
    doc.rect(50, y, 240, 80).fillColor('#F8FAFC').fill().rect(50, y, 240, 80).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.rect(305, y, 240, 80).fillColor('#F8FAFC').fill().rect(305, y, 240, 80).strokeColor(LGREY).lineWidth(0.5).stroke();

    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('BILL TO', 65, y + 10);
    doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
      .text(client.name, 65, y + 22)
      .text(client.address || '', 65, y + 34, { width: 210 })
      .text(`KRA PIN: ${client.kra_pin || 'N/A'}`, 65, y + 58);

    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('INVOICE DETAILS', 320, y + 10);
    doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
      .text(`Invoice No:`, 320, y + 22).text(invoice.invoice_no, 395, y + 22, { align: 'right', width: 140 })
      .text(`Date:`, 320, y + 34).text(dateStr(invoice.date), 395, y + 34, { align: 'right', width: 140 })
      .text(`Due Date:`, 320, y + 46).text(dateStr(invoice.due_date) || '30 days', 395, y + 46, { align: 'right', width: 140 })
      .text(`Currency:`, 320, y + 58).text('KES', 395, y + 58, { align: 'right', width: 140 });

    y += 95;

    // Line items table header
    doc.rect(50, y, 495, 20).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff')
      .text('DESCRIPTION', 65, y + 6)
      .text('QTY', 340, y + 6)
      .text('UNIT PRICE', 380, y + 6)
      .text('VAT CAT', 440, y + 6)
      .text('AMOUNT', 490, y + 6, { align: 'right', width: 50 });
    y += 20;

    (lines || []).forEach((line, i) => {
      const rowH = 22;
      if (i % 2 === 0) doc.rect(50, y, 495, rowH).fillColor('#FAFAFA').fill();
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text(line.description, 65, y + 6, { width: 270 })
        .text(String(line.quantity || 1), 340, y + 6)
        .text(kes(line.unit_price || line.amount), 375, y + 6)
        .text(line.vat_category || 'A', 447, y + 6)
        .text(kes(line.amount || line.exclusive), 490, y + 6, { align: 'right', width: 50 });
      y += rowH;
    });

    // Totals
    y += 5;
    drawHRule(doc, y);
    y += 8;

    const subtotal   = invoice.subtotal || lines.reduce((s, l) => s + (l.amount || l.exclusive || 0), 0);
    const vatAmount  = invoice.vat_amount || 0;
    const total      = invoice.total || subtotal + vatAmount;

    [['Subtotal (excl. VAT)', subtotal], ['VAT @ 16%', vatAmount]].forEach(([label, amount]) => {
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
        .text(label, 350, y)
        .text(kes(amount), 0, y, { align: 'right', width: 540 });
      y += 16;
    });

    doc.rect(50, y, 495, 28).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD)
      .text('TOTAL DUE', 65, y + 9)
      .text(kes(total), 0, y + 9, { align: 'right', width: 540 });
    y += 36;

    // KRA eTIMS info
    doc.rect(50, y, 495, 32).fillColor('#F0F9F4').fill().rect(50, y, 495, 32).strokeColor('#86EFAC').lineWidth(0.5).stroke();
    doc.font('Helvetica-Bold').fontSize(8).fillColor(GREEN).text('KRA eTIMS', 65, y + 8);
    doc.font('Helvetica').fontSize(7.5).fillColor(DKGREY)
      .text(`CU Invoice No: ${invoice.etims_cu_no || 'Pending submission'}`, 65, y + 20)
      .text(`QSL KRA PIN: ${_company.kra_pin}`, 280, y + 20);
    y += 40;

    // Payment details
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('PAYMENT INSTRUCTIONS', 50, y);
    y += 12;
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text('Bank Transfer: Equity Bank Kenya · A/C: [Account Number] · Branch: [Branch]', 50, y)
      .text(`M-PESA Paybill: ${process.env.MPESA_SHORTCODE || '[Paybill]'} · Account: ${invoice.invoice_no}`, 50, y + 12);

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/invoices/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── CALIBRATION CERTIFICATE PDF ───────────────────────────────────────────────

async function generateCalibrationCert(cert, client, technician, refStandard) {
  const dir  = path.join(UPLOAD_DIR, 'certificates');
  ensureDir(dir);
  const file = path.join(dir, `cert_${cert.cert_no.replace(/\//g,'_')}.pdf`);
  const qrBuffer = await getQrBuffer(cert.cert_no);
  const docCode = cert.cert_no || 'QSL/QP/19/CERT';
  const techName = technician?.first_name ? `${technician.first_name} ${technician.last_name}` : '—';
  const checkerName = cert.checked_by_name || '________________';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    const runningHeader = (page, total) => {
      doc.font('Helvetica-Oblique').fontSize(7).fillColor(GREY)
        .text('ISO/IEC 17025 Calibration Laboratory — KENAS Accredited CL/059', 50, 30)
        .text(`Document generated by QSL-CMS`, 0, 30, { align: 'right', width: 495 });
      doc.font('Helvetica-Bold').fontSize(20).fillColor(GOLD).text('QSL', 50, 44);
      doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(_company.legal_name, 95, 48);
      doc.font('Helvetica-Bold').fontSize(7).fillColor(DKGREY).text('ilac-MRA', 0, 44, { align: 'right', width: 420 });
      doc.font('Helvetica-Bold').fontSize(7).fillColor(NAVY).text('KENAS CL/059', 0, 56, { align: 'right', width: 420 });
      if (qrBuffer) doc.image(qrBuffer, 497, 40, { width: 48, height: 48 });
      drawHRule(doc, 78, LGREY);
      doc.font('Helvetica').fontSize(7).fillColor(GREY).text(`Page ${page} of ${total}`, 0, 30, { align: 'right', width: 545 });
    };

    const runningFooter = () => {
      const bottom = doc.page.height - 100;
      doc.rect(50, bottom, 495, 1).fill(GOLD);
      doc.font('Helvetica-Bold').fontSize(7).fillColor(DKGREY)
        .text(`${_company.legal_name} - QSL CENTRE, ${_company.address}`, 50, bottom + 6, { width: 495, align: 'center', lineBreak: false });
      doc.font('Helvetica').fontSize(7).fillColor(GREY)
        .text(`P.O Box 34463-00100 GPO Nairobi Kenya  Cell: ${_company.phone}`, 50, bottom + 15, { width: 495, align: 'center', lineBreak: false });
      doc.font('Helvetica').fontSize(6.5).fillColor(GREY)
        .text(`Mail: ${_company.email}`, 50, bottom + 24, { width: 495, align: 'center', lineBreak: false });
      doc.font('Helvetica-Oblique').fontSize(6.5).fillColor(GREY)
        .text(`${docCode} — This is a system-generated certificate, validated with digital signatures.`, 50, bottom + 33, { width: 495, align: 'center', lineBreak: false });
    };

    // ── PAGE 1 ──────────────────────────────────────────────────────────────
    runningHeader(1, 2);
    let y = 96;

    doc.font('Helvetica-Bold').fontSize(18).fillColor(NAVY).text('CALIBRATION CERTIFICATE', 50, y);
    doc.rect(50, y + 22, 130, 2).fill(GOLD);
    y += 30;
    doc.font('Helvetica-Oblique').fontSize(9).fillColor(DKGREY).text(cert.instrument || 'Instrument Calibration', 50, y);
    y += 20;

    // Object-of-calibration info box
    const infoRows = [
      ['CERTIFICATE NO.', cert.cert_no],
      ['REQUESTED BY', client?.name || '—'],
      ['ADDRESS', client?.address || '—'],
      ['EQUIPMENT', cert.instrument || '—'],
      ['TYPE / MODEL', cert.model || '—'],
      ['MANUFACTURER', cert.make || '—'],
      ['SERIAL NUMBER', cert.serial_no || '—'],
      ['LOCATION', cert.location || 'QSL Calibration Laboratory'],
      ['CALIBRATION DATE', dateStr(cert.calibrated_at)],
      ['CERTIFICATE EXPIRY', dateStr(cert.next_cal_date)],
    ];
    const boxH = infoRows.length * 16 + 10;
    doc.rect(50, y, 495, boxH).fill('#F0F2F5');
    infoRows.forEach(([label, value], i) => {
      const ry = y + 8 + i * 16;
      doc.font('Helvetica-Bold').fontSize(8).fillColor(DKGREY).text(label, 62, ry);
      doc.font('Helvetica').fontSize(8).fillColor(NAVY).text(String(value ?? '—'), 230, ry, { width: 300 });
    });
    y += boxH + 16;

    const sectionHeader = (num, title) => {
      doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(`${num} ${title}`, 50, y);
      doc.moveTo(50, y + 12).lineTo(545, y + 12).strokeColor(LGREY).lineWidth(0.6).stroke();
      y += 18;
    };
    const para = (text) => {
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(text, 50, y, { width: 495, align: 'justify' });
      y = doc.y + 6;
    };

    sectionHeader('1.0', 'REFERENCE STANDARDS AND EQUIPMENT USED');
    para(`The instrument was calibrated against ${refStandard?.name || 'a calibrated reference standard'}` +
      (refStandard?.traceable_to ? `, traceable to ${refStandard.traceable_to} national standards.` : '.'));

    sectionHeader('2.0', 'METROLOGICAL TRACEABILITY');
    para('This calibration certificate documents traceability to the national measurement standards, and to the units of measurement realized at KEBS, or other recognized national standards laboratories, according to the International System of Units (SI).');

    sectionHeader('3.0', 'CALIBRATION PROCEDURE');
    para(cert.procedure_ref || `QSL/QP/19 — Standard QSL Calibration Procedure for ${cert.instrument || 'this instrument class'}.`);

    sectionHeader('4.0', 'ENVIRONMENTAL CONDITIONS');
    const envY = y;
    const hasEnd = cert.temp_c_end != null || cert.humidity_pct_end != null;
    doc.rect(50, envY, 247, 30).fill('#F8FAFC').rect(50, envY, 247, 30).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.rect(298, envY, 247, 30).fill('#F8FAFC').rect(298, envY, 247, 30).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.font('Helvetica-Bold').fontSize(7.5).fillColor(GREY).text(hasEnd ? 'TEMPERATURE (START -> END)' : 'TEMPERATURE', 62, envY + 6);
    doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(
      cert.temp_c ? `${cert.temp_c} °C${hasEnd && cert.temp_c_end != null ? ` -> ${cert.temp_c_end} °C` : ''}` : '—', 62, envY + 16);
    doc.font('Helvetica-Bold').fontSize(7.5).fillColor(GREY).text(hasEnd ? 'RELATIVE HUMIDITY (START -> END)' : 'RELATIVE HUMIDITY', 310, envY + 6);
    doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(
      cert.humidity_pct ? `${cert.humidity_pct} %${hasEnd && cert.humidity_pct_end != null ? ` -> ${cert.humidity_pct_end} %` : ''}` : '—', 310, envY + 16);
    y = envY + 40;

    sectionHeader('5.0', 'VALIDITY AND AUTHORIZATION');
    const sigY = y;
    const colW = 165;
    ['VALIDITY', 'CALIBRATED BY', 'CHECKED BY'].forEach((h, i) => {
      doc.rect(50 + i * colW, sigY, colW - (i < 2 ? 2 : 0), 20).fill(NAVY);
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, 50 + i * colW, sigY + 6, { width: colW, align: 'center' });
    });
    const sigBoxY = sigY + 20;
    doc.rect(50, sigBoxY, colW * 3, 50).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.moveTo(50 + colW, sigBoxY).lineTo(50 + colW, sigBoxY + 50).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.moveTo(50 + colW * 2, sigBoxY).lineTo(50 + colW * 2, sigBoxY + 50).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY).text(cert.validity_note || 'Valid until next calibration date', 58, sigBoxY + 10, { width: colW - 16 });
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text(techName, 58 + colW, sigBoxY + 30, { width: colW - 16, align: 'center' });
    doc.moveTo(58 + colW, sigBoxY + 27).lineTo(58 + colW + colW - 16, sigBoxY + 27).strokeColor(DKGREY).lineWidth(0.5).stroke();
    doc.font('Helvetica').fontSize(7).fillColor(GREY).text(`[${dateStr(cert.calibrated_at)}]`, 58 + colW, sigBoxY + 40, { width: colW - 16, align: 'center' });
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text(checkerName, 58 + colW * 2, sigBoxY + 30, { width: colW - 16, align: 'center' });
    doc.moveTo(58 + colW * 2, sigBoxY + 27).lineTo(58 + colW * 2 + colW - 16, sigBoxY + 27).strokeColor(DKGREY).lineWidth(0.5).stroke();
    doc.font('Helvetica').fontSize(7).fillColor(GREY).text(`[${cert.checked_at ? dateStr(cert.checked_at) : 'pending'}]`, 58 + colW * 2, sigBoxY + 40, { width: colW - 16, align: 'center' });
    y = sigBoxY + 64;

    doc.rect(50, y, 495, 24).fill(NAVY);
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#ffffff')
      .text('This certificate was issued without any erasure or alteration whatsoever', 50, y + 8, { width: 495, align: 'center' });

    runningFooter();
    doc.addPage();

    // ── PAGE 2 — MEASUREMENT RESULTS ─────────────────────────────────────────
    runningHeader(2, 2);
    y = 96;
    sectionHeaderP2(doc, y, '6.0', 'MEASUREMENT RESULTS'); y += 18;

    const passed = cert.result === 'pass' || cert.result === 'adjusted';
    const isNawi = cert.instrument_type === 'nawi' && cert.nawi;
    const ensureRoom = (needed) => { if (y + needed > doc.page.height - 110) { runningFooter(); doc.addPage(); runningHeader(2, 2); y = 96; } };

    const drawTable = (cols, rows, rowColor) => {
      let cx = 50;
      doc.rect(50, y, 495, 18).fill(NAVY);
      cols.forEach(c => { doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#ffffff').text(c.label, cx + 4, y + 5, { width: c.w - 6 }); cx += c.w; });
      y += 18;
      rows.forEach((r, ri) => {
        ensureRoom(16);
        if (ri % 2 === 0) doc.rect(50, y, 495, 16).fill('#F8FAFC');
        cx = 50;
        cols.forEach((c, ci) => {
          doc.font('Helvetica').fontSize(7.5).fillColor(rowColor ? rowColor(r) : DKGREY).text(String(r[ci] ?? '—'), cx + 4, y + 4, { width: c.w - 6 });
          cx += c.w;
        });
        y += 16;
      });
      y += 10;
    };

    if (isNawi) {
      // EURAMET cg-18 §8.3 — error of indication at each applied test load
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text('Error of indication — results at each applied test load (EURAMET cg-18 §4 step 4):', 50, y, { width: 495 });
      y = doc.y + 8;
      drawTable(
        [{ label: 'TEST LOAD', w: 140 }, { label: 'INDICATION', w: 120 }, { label: 'ERROR', w: 110 }, { label: 'UNCERTAINTY (± k=2)', w: 125 }],
        cert.nawi.test_points.map(p => [p.test_load, p.indication ?? '—', p.error ?? '—', p.uncertainty ?? '—'])
      );

      ensureRoom(60);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text(`Eccentricity test (cg-18 §4 step 3):`, 50, y, { width: 495 });
      y = doc.y + 8;
      if (cert.nawi.eccentricity?.length) {
        drawTable(
          [{ label: 'POSITION', w: 165 }, { label: 'INDICATION', w: 165 }, { label: 'DEVIATION FROM CENTRE', w: 165 }],
          cert.nawi.eccentricity.map(e => [e.position, e.indication ?? '—', e.deviation ?? '—'])
        );
      } else {
        doc.font('Helvetica-Oblique').fontSize(8).fillColor(GREY).text('Omitted — construction-related restrictions make eccentric loading impossible.', 50, y, { width: 495 });
        y = doc.y + 14;
      }

      ensureRoom(50);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text(`Repeatability test (cg-18 §4 step 2) — ${cert.nawi.repeatability.length} readings of the same load:`, 50, y, { width: 495 });
      y = doc.y + 8;
      const repVals = cert.nawi.repeatability.map(r => r.indication).filter(v => v !== null && v !== undefined);
      drawTable(
        [{ label: '#', w: 40 }, ...cert.nawi.repeatability.map((_, i) => ({ label: `R${i + 1}`, w: Math.floor(455 / cert.nawi.repeatability.length) }))],
        [['Indication', ...repVals]]
      );
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor(NAVY)
        .text(`Standard deviation: ${cert.repeatability_stdev != null ? Number(cert.repeatability_stdev).toFixed(4) : '—'}`, 50, y);
      if (cert.min_weight) doc.font('Helvetica-Bold').fontSize(8.5).fillColor(NAVY).text(`Minimum weight: ${cert.min_weight}`, 300, y);
      y += 20;

      ensureRoom(20);
      doc.rect(50, y, 495, 22).fill(passed ? '#F0FFF4' : '#FFF0F0');
      doc.font('Helvetica-Bold').fontSize(9).fillColor(passed ? GREEN : RED)
        .text(passed ? 'OVERALL RESULT: PASS — within declared tolerance class' : 'OVERALL RESULT: FAIL — outside declared tolerance class', 60, y + 6);
      y += 32;
    } else {
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text('Results below relate to the item(s) identified in Section 1.0 of this certificate.', 50, y, { width: 495 });
      y += 22;
      const cols = [
        { label: 'PARAMETER', w: 110 }, { label: 'NOMINAL / RANGE', w: 110 },
        { label: 'READING / RESULT', w: 110 }, { label: 'UNCERTAINTY (± k=2)', w: 100 }, { label: 'PASS/FAIL', w: 65 },
      ];
      let cx = 50;
      doc.rect(50, y, 495, 20).fill(NAVY);
      cols.forEach(c => { doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(c.label, cx + 5, y + 6, { width: c.w - 8 }); cx += c.w; });
      y += 20;
      const row = [cert.instrument || '—', cert.range || '—', passed ? 'Within tolerance' : 'Out of tolerance', cert.uncertainty || '—', passed ? 'PASS' : 'FAIL'];
      cx = 50;
      doc.rect(50, y, 495, 22).fill('#F8FAFC');
      cols.forEach((c, i) => {
        doc.font('Helvetica-Bold').fontSize(8).fillColor(i === 4 ? (passed ? GREEN : RED) : DKGREY)
          .text(row[i], cx + 5, y + 7, { width: c.w - 8 });
        cx += c.w;
      });
      y += 22 + 16;
    }

    ensureRoom(80);
    sectionHeaderP2(doc, y, '7.0', 'COMMENTS'); y += 18;
    [
      'The results in clause 6.0 relate only to the item(s) calibrated.',
      `All calibrated parameters ${passed ? 'fall within the specified tolerance.' : 'were assessed against the specified tolerance — see result above.'}`,
      'The reported expanded uncertainty is based on a standard uncertainty multiplied by a coverage factor k = 2, providing a level of confidence of approximately 95%, unless stated otherwise.',
    ].forEach((t, i) => {
      ensureRoom(20);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(`${i + 1}. ${t}`, 50, y, { width: 495 });
      y = doc.y + 4;
    });
    y += 8;

    ensureRoom(70);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text('— END OF CERTIFICATE —', 50, y, { width: 495, align: 'center' });
    y += 24;

    doc.rect(50, y, 60, 14).fill('#FBBF24');
    doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#000').text('NOTE', 50, y + 4, { width: 60, align: 'center' });
    y += 18;
    doc.font('Helvetica-Oblique').fontSize(8).fillColor(DKGREY)
      .text('This certificate shall not be reproduced except in full without the written approval of the Laboratory. Results relate only to the items calibrated.', 50, y, { width: 495 });

    runningFooter();
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/certificates/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

function sectionHeaderP2(doc, y, num, title) {
  doc.font('Helvetica-Bold').fontSize(9).fillColor(NAVY).text(`${num} ${title}`, 50, y);
  doc.moveTo(50, y + 12).lineTo(545, y + 12).strokeColor(LGREY).lineWidth(0.6).stroke();
}

// ── AGED DEBTORS REPORT PDF ───────────────────────────────────────────────────

async function generateAgedDebtorsReport(clients, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().split('T')[0];
  const file = path.join(dir, `aged_debtors_${date}.pdf`);
  const qrBuffer = await getQrBuffer(`AGED-DEBTORS-${date}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, 'AGED DEBTORS REPORT', `Generated: ${dateStr(new Date())} by ${generatedBy}`, qrBuffer);

    let y = 110;
    const total = clients.reduce((s, c) => s + (c.outstanding || 0), 0);

    // Summary box
    doc.rect(50, y, 745, 35).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD)
      .text(`Total Outstanding: ${kes(total)}`, 65, y + 13)
      .text(`${clients.length} Clients`, 0, y + 13, { align: 'right', width: 790 });
    y += 45;

    // Table header
    const cols = [65, 280, 390, 470, 560, 680];
    const headers = ['Client Name', 'Contact', 'Account Owner', 'Outstanding (Kshs)', 'Credit Limit', 'Status'];
    doc.rect(50, y, 745, 20).fillColor('#334155').fill();
    headers.forEach((h, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6);
    });
    y += 20;

    clients.forEach((c, i) => {
      const rowH = 18;
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#F8FAFC').fill();
      doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
        .text(c.name, cols[0], y + 5, { width: 210 })
        .text(c.contact_person || '—', cols[1], y + 5, { width: 105 })
        .text(c.account_owner || '—', cols[2], y + 5, { width: 75 })
        .text(kes(c.outstanding), cols[3], y + 5, { width: 85 })
        .text(kes(c.credit_limit || 0), cols[4], y + 5, { width: 115 });
      doc.font('Helvetica-Bold').fontSize(8).fillColor(c.outstanding > 0 ? RED : GREEN)
        .text(c.outstanding > 0 ? 'OUTSTANDING' : 'CLEARED', cols[5], y + 5);
      y += rowH;

      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
      }
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── AUDIT TRAIL EXPORT PDF ────────────────────────────────────────────────────

async function generateAuditTrail(entries, filters, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const file = path.join(dir, `audit_trail_${date}.pdf`);
  const qrBuffer = await getQrBuffer(`AUDIT-TRAIL-${date}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, 'AUDIT TRAIL EXPORT', `Generated: ${dateStr(new Date())} · ${entries.length} records · By: ${generatedBy}`, qrBuffer);

    let y = 110;
    if (filters) {
      doc.font('Helvetica').fontSize(8).fillColor(GREY)
        .text(`Filters — Module: ${filters.module || 'All'} | User: ${filters.user || 'All'} | Date: ${filters.from || '—'} to ${filters.to || '—'}`, 50, y);
      y += 20;
    }

    const cols = [50, 165, 255, 340, 440, 560];
    const headers = ['Timestamp', 'User', 'Module', 'Action', 'Record ID', 'Details'];
    doc.rect(50, y, 745, 20).fillColor(NAVY).fill();
    headers.forEach((h, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6);
    });
    y += 20;

    entries.forEach((e, i) => {
      const rowH = 16;
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#FAFAFA').fill();
      doc.font('Helvetica').fontSize(7).fillColor(DKGREY)
        .text(new Date(e.created_at).toLocaleString('en-KE'), cols[0], y + 4, { width: 110 })
        .text(e.user_name || '—', cols[1], y + 4, { width: 85 })
        .text(e.module, cols[2], y + 4, { width: 80 })
        .text(e.action, cols[3], y + 4, { width: 95 })
        .text(e.record_id ? e.record_id.slice(0, 12) + '…' : '—', cols[4], y + 4, { width: 115 })
        .text(e.new_value ? JSON.stringify(e.new_value).slice(0, 40) : '', cols[5], y + 4, { width: 185 });
      y += rowH;

      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
        // Re-draw header on new page
        doc.rect(50, y, 745, 20).fillColor(NAVY).fill();
        headers.forEach((h, i) => doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6));
        y += 20;
      }
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── PROFIT & LOSS STATEMENT PDF ───────────────────────────────────────────────

async function generateProfitAndLoss(plData, period, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const file = path.join(dir, `pnl_${period.replace(/[\s\/]/g,'_')}.pdf`);
  const qrBuffer = await getQrBuffer(`PNL-${period}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'PROFIT & LOSS STATEMENT', `Period: ${period}`, qrBuffer);
    y = 110;

    doc.font('Helvetica').fontSize(8).fillColor(GREY)
      .text(`Generated: ${dateStr(new Date())} by ${generatedBy} · All figures in Kenya Shillings (Kshs)`, 50, y);
    y += 18;

    const section = (label, rows, total, totalColor = NAVY, fillHeader = NAVY) => {
      doc.rect(50, y, 495, 18).fillColor(fillHeader).fill();
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text(label, 65, y + 5);
      y += 18;
      rows.forEach((r, i) => {
        if (i % 2 === 0) doc.rect(50, y, 495, 16).fillColor('#F8FAFC').fill();
        doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(r.name, 65, y + 4, { width: 350 });
        doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(kes(r.amount), 0, y + 4, { align: 'right', width: 530 });
        y += 16;
      });
      doc.rect(50, y, 495, 20).fillColor('#F0F4F8').fill();
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(totalColor).text(`Total ${label}`, 65, y + 5);
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(totalColor).text(kes(total), 0, y + 5, { align: 'right', width: 530 });
      y += 28;
    };

    if (!plData.has_gl_data) {
      doc.rect(50, y, 495, 50).fillColor('#FFFBEB').fill().rect(50, y, 495, 50).strokeColor('#FCD34D').lineWidth(0.5).stroke();
      doc.font('Helvetica-Bold').fontSize(10).fillColor(AMBER).text('No General Ledger postings found for this period.', 65, y + 12);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text('Post journal entries via Finance → Journal Entries for figures to appear here. This statement will populate automatically once postings exist.', 65, y + 28, { width: 460 });
      y += 60;
    }

    section('Revenue', plData.revenue, plData.totalRevenue, GREEN, NAVY);
    section('Cost of Sales', plData.cogs, plData.totalCOGS, RED, NAVY);

    doc.rect(50, y, 495, 24).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text('GROSS PROFIT', 65, y + 7);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text(kes(plData.grossProfit), 0, y + 7, { align: 'right', width: 530 });
    doc.font('Helvetica').fontSize(7).fillColor('#C8D4DE').text(`Margin: ${plData.totalRevenue ? ((plData.grossProfit/plData.totalRevenue)*100).toFixed(1) : '0.0'}%`, 65, y + 17);
    y += 34;

    section('Operating Expenses', plData.opex, plData.totalOpex, RED, NAVY);
    section('Depreciation & Amortisation', plData.depreciation, plData.totalDepreciation, RED, NAVY);

    doc.rect(50, y, 495, 24).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text('OPERATING PROFIT (EBIT)', 65, y + 7);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text(kes(plData.operatingProfit), 0, y + 7, { align: 'right', width: 530 });
    y += 34;

    if (plData.otherIncome.length || plData.financeCosts.length) {
      section('Other Income', plData.otherIncome, plData.totalOtherIncome, GREEN, NAVY);
      section('Finance Costs', plData.financeCosts, plData.totalFinanceCosts, RED, NAVY);
    }

    doc.rect(50, y, 495, 36).fillColor(plData.netProfit >= 0 ? GREEN : RED).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#ffffff').text('NET PROFIT / (LOSS)', 65, y + 13);
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#ffffff').text(kes(plData.netProfit), 0, y + 13, { align: 'right', width: 530 });
    y += 46;

    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text('Prepared in accordance with the QSL Chart of Accounts (ICPAK-aligned). This statement is system-generated from posted General Ledger journal entries.', 50, y, { width: 495 });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── GENERIC TABULAR REPORT PDF (point 4 — Reporting exports) ─────────────────
// Shared by Inventory, Requisitions, Vehicles, and User Activity reports so
// each doesn't need its own near-identical layout function. Caller supplies
// the title, column definitions, rows, and an optional filter summary line.

async function generateTabularReport({ title, subtitle, filtersSummary, columns, rows, generatedBy, filenamePrefix }) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().split('T')[0];
  const file = path.join(dir, `${filenamePrefix || 'report'}_${date}.pdf`);
  const qrBuffer = await getQrBuffer(`${filenamePrefix || 'report'}-${date}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, title, subtitle || `Generated: ${dateStr(new Date())} by ${generatedBy}`, qrBuffer);

    let y = 110;

    if (filtersSummary) {
      doc.font('Helvetica').fontSize(8).fillColor(GREY).text(`Filters: ${filtersSummary}`, 50, y);
      y += 16;
    }

    doc.rect(50, y, 745, 26).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD)
      .text(`${rows.length} record(s)`, 65, y + 8);
    y += 36;

    // Compute column widths proportionally across the 745pt usable width
    const totalWeight = columns.reduce((s, c) => s + (c.weight || 1), 0);
    const usableWidth  = 745;
    let cursorX = 50;
    const colX = [];
    columns.forEach(c => {
      colX.push(cursorX);
      cursorX += (usableWidth * (c.weight || 1)) / totalWeight;
    });

    doc.rect(50, y, 745, 20).fillColor('#334155').fill();
    columns.forEach((c, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(c.label, colX[i] + 5, y + 6, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8 });
    });
    y += 20;

    rows.forEach((row, i) => {
      const rowH = 18;
      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
      }
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#F8FAFC').fill();
      columns.forEach((c, ci) => {
        const val = c.format ? c.format(row[c.key], row) : (row[c.key] ?? '—');
        doc.font('Helvetica').fontSize(8).fillColor(c.color ? c.color(row[c.key], row) : DKGREY)
          .text(String(val), colX[ci] + 5, y + 5, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8 });
      });
      y += rowH;
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

module.exports = {
  loadCompany,
  generatePayslip,
  generateInvoice,
  generateCalibrationCert,
  generateAgedDebtorsReport,
  generateAuditTrail,
  generateProfitAndLoss,
  generateTabularReport,
  generateBusinessDoc,
  DOC_TYPES,
};
