// src/lib/pdf.js — PDF Generator (PDFKit)
// Generates: payslips, tax invoices, calibration certificates, audit trail exports

const PDFDocument = require('pdfkit');
const path   = require('path');
const fs     = require('fs');

const NAVY   = '#1B3A5C';
const GOLD   = '#C8960C';
const GREY   = '#94A3B8';
const DKGREY = '#334155';
const LGREY  = '#E8ECF0';
const GREEN  = '#1E6B3C';
const RED    = '#C00000';

const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads');

// Company identity shown on every PDF. Defaults match the original hardcoded
// values; loadCompany() refreshes them from System Settings (company.*) and
// should be called once before generating a document. It's a shared global
// (company identity is the same for all requests), so caching is safe.
let _company = {
  legal_name: 'QALIBRATED SYSTEMS LIMITED',
  address:    'Birdi Singh Complex, Off Mombasa Road, Nairobi',
  email:      'info@qalibrated.co.ke',
  phone:      '+254 714 999 996',
  kra_pin:    'P000000001K',
};
async function loadCompany() {
  try {
    const c = await require('./settings').getCompany();
    if (c && c.legal_name) _company = { ...c };
  } catch { /* keep defaults */ }
}

// ── HELPERS ───────────────────────────────────────────────────────────────────

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function kes(n) {
  return `Kshs ${Number(n||0).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`;
}

function dateStr(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-KE', { day: '2-digit', month: 'long', year: 'numeric' });
}

function drawHRule(doc, y, color = LGREY) {
  doc.moveTo(50, y).lineTo(545, y).strokeColor(color).lineWidth(0.5).stroke();
}

function addHeader(doc, title, subtitle = '') {
  // Navy header bar
  doc.rect(0, 0, 595, 80).fill(NAVY);
  doc.rect(0, 80, 595, 6).fill(GOLD);

  // Company name
  doc.font('Helvetica-Bold').fontSize(18).fillColor(GOLD).text('QSL', 50, 22);
  doc.font('Helvetica').fontSize(8).fillColor('#aabbcc').text(_company.legal_name, 50, 44);
  doc.font('Helvetica').fontSize(7).fillColor('#8899aa').text(`${_company.address}  |  ${_company.email}  |  ${_company.phone}`, 50, 56);

  // Title on right
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#ffffff').text(title, 0, 26, { align: 'right', width: 545 });
  if (subtitle) doc.font('Helvetica').fontSize(9).fillColor(GOLD).text(subtitle, 0, 46, { align: 'right', width: 545 });

  doc.moveDown(0.5);
  return 100; // y position after header
}

function addFooter(doc) {
  const bottom = doc.page.height - 50;
  drawHRule(doc, bottom - 10, LGREY);
  doc.font('Helvetica').fontSize(7).fillColor(GREY)
    .text('This document is generated by QSL ERP. For queries: info@qalibrated.co.ke', 50, bottom, { align: 'center', width: 495 });
}

// ── PAYSLIP PDF ───────────────────────────────────────────────────────────────

async function generatePayslip(employee, payslip, period) {
  const dir  = path.join(UPLOAD_DIR, 'payslips');
  ensureDir(dir);
  const file = path.join(dir, `payslip_${employee.emp_no}_${period.replace('-', '_')}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'PAYSLIP', period);
    y = 110;

    // Employee details box
    doc.rect(50, y, 495, 70).fillColor('#F0F4F8').fill();
    doc.rect(50, y, 495, 70).strokeColor(LGREY).lineWidth(0.5).stroke();

    doc.font('Helvetica-Bold').fontSize(10).fillColor(NAVY).text(employee.first_name + ' ' + employee.last_name, 65, y + 12);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`Employee No: ${employee.emp_no}`, 65, y + 26)
      .text(`Department: ${employee.department}`, 65, y + 38)
      .text(`Role: ${employee.role}`, 65, y + 50);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`KRA PIN: ${employee.kra_pin || '—'}`, 310, y + 26)
      .text(`NHIF No: ${employee.nhif_no || '—'}`, 310, y + 38)
      .text(`NSSF No: ${employee.nssf_no || '—'}`, 310, y + 50)
      .text(`Pay Date: ${dateStr(new Date())}`, 310, y + 62 - 12);

    y += 85;

    // Earnings section
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text('EARNINGS', 65, y + 5);
    y += 18;

    const earnings = [
      ['Basic Salary', payslip.basic_salary],
      ['Allowances', payslip.allowances || 0],
    ];
    earnings.forEach(([label, amount], i) => {
      if (i % 2 === 0) doc.rect(50, y, 495, 18).fillColor('#F8FAFC').fill();
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
        .text(label, 65, y + 5)
        .text(kes(amount), 0, y + 5, { align: 'right', width: 540 });
      y += 18;
    });

    // Gross
    doc.rect(50, y, 495, 22).fillColor('#E8F5E9').fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GREEN)
      .text('GROSS PAY', 65, y + 6)
      .text(kes(payslip.gross_pay), 0, y + 6, { align: 'right', width: 540 });
    y += 28;

    // Deductions
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text('STATUTORY DEDUCTIONS', 65, y + 5);
    y += 18;

    const deductions = [
      ['PAYE (Income Tax)', payslip.paye, 'KRA — computed on progressive bands'],
      ['NHIF / SHIF', payslip.nhif, '2.75% of gross — NHIF/SHIF'],
      ['NSSF (Tier I + II)', payslip.nssf, '6% on Tier I (≤7,000) + 6% on Tier II (≤36,000)'],
      ['Affordable Housing Levy', payslip.housing_levy, '1.5% of gross (Finance Act 2023)'],
    ];
    if (payslip.imprest_deductions > 0) deductions.push(['Imprest Recovery', payslip.imprest_deductions, 'Outstanding imprest advance recovery']);
    if (payslip.other_deductions > 0)   deductions.push(['Other Deductions', payslip.other_deductions, '']);

    deductions.forEach(([label, amount, note], i) => {
      if (i % 2 === 0) doc.rect(50, y, 495, 22).fillColor('#FFF8F8').fill();
      doc.font('Helvetica-Bold').fontSize(9).fillColor(RED).text(`(${kes(amount)})`, 0, y + 5, { align: 'right', width: 540 });
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY).text(label, 65, y + 5);
      if (note) doc.font('Helvetica').fontSize(7).fillColor(GREY).text(note, 65, y + 15);
      y += (note ? 24 : 18);
    });

    // Total deductions
    const totalDed = payslip.total_deductions || (payslip.paye + payslip.nhif + payslip.nssf + payslip.housing_levy + (payslip.imprest_deductions||0) + (payslip.other_deductions||0));
    doc.rect(50, y, 495, 20).fillColor('#FEE2E2').fill();
    doc.font('Helvetica-Bold').fontSize(9).fillColor(RED)
      .text('TOTAL DEDUCTIONS', 65, y + 6)
      .text(`(${kes(totalDed)})`, 0, y + 6, { align: 'right', width: 540 });
    y += 26;

    // Net pay — big box
    doc.rect(50, y, 495, 40).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(13).fillColor(GOLD).text('NET PAY', 65, y + 13);
    doc.font('Helvetica-Bold').fontSize(16).fillColor(GOLD).text(kes(payslip.net_pay), 0, y + 11, { align: 'right', width: 540 });
    y += 50;

    // Employer contributions note
    doc.rect(50, y, 495, 50).fillColor('#F0F4F8').fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('EMPLOYER CONTRIBUTIONS (not deducted from salary)', 65, y + 8);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`NSSF Employer:  ${kes(payslip.employer_nssf || payslip.nssf)}`, 65, y + 22)
      .text(`Housing Levy Employer:  ${kes(payslip.employer_housing || payslip.housing_levy)}`, 250, y + 22);
    y += 60;

    // Digital signature notice
    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text('This payslip is digitally signed and verified by QSL ERP (ARCH-007B). For disputes contact HR within 5 working days of receipt.', 50, y, { width: 495, align: 'center' });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/payslips/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── TAX INVOICE PDF ───────────────────────────────────────────────────────────

async function generateInvoice(invoice, client, lines) {
  const dir  = path.join(UPLOAD_DIR, 'invoices');
  ensureDir(dir);
  const file = path.join(dir, `invoice_${invoice.invoice_no.replace(/\//g,'_')}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'TAX INVOICE', invoice.invoice_no);
    y = 110;

    // Invoice meta + client info
    doc.rect(50, y, 240, 80).fillColor('#F8FAFC').fill().rect(50, y, 240, 80).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.rect(305, y, 240, 80).fillColor('#F8FAFC').fill().rect(305, y, 240, 80).strokeColor(LGREY).lineWidth(0.5).stroke();

    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('BILL TO', 65, y + 10);
    doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
      .text(client.name, 65, y + 22)
      .text(client.address || '', 65, y + 34, { width: 210 })
      .text(`KRA PIN: ${client.kra_pin || 'N/A'}`, 65, y + 58);

    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('INVOICE DETAILS', 320, y + 10);
    doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
      .text(`Invoice No:`, 320, y + 22).text(invoice.invoice_no, 395, y + 22, { align: 'right', width: 140 })
      .text(`Date:`, 320, y + 34).text(dateStr(invoice.date), 395, y + 34, { align: 'right', width: 140 })
      .text(`Due Date:`, 320, y + 46).text(dateStr(invoice.due_date) || '30 days', 395, y + 46, { align: 'right', width: 140 })
      .text(`Currency:`, 320, y + 58).text('KES', 395, y + 58, { align: 'right', width: 140 });

    y += 95;

    // Line items table header
    doc.rect(50, y, 495, 20).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff')
      .text('DESCRIPTION', 65, y + 6)
      .text('QTY', 340, y + 6)
      .text('UNIT PRICE', 380, y + 6)
      .text('VAT CAT', 440, y + 6)
      .text('AMOUNT', 490, y + 6, { align: 'right', width: 50 });
    y += 20;

    (lines || []).forEach((line, i) => {
      const rowH = 22;
      if (i % 2 === 0) doc.rect(50, y, 495, rowH).fillColor('#FAFAFA').fill();
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
        .text(line.description, 65, y + 6, { width: 270 })
        .text(String(line.quantity || 1), 340, y + 6)
        .text(kes(line.unit_price || line.amount), 375, y + 6)
        .text(line.vat_category || 'A', 447, y + 6)
        .text(kes(line.amount || line.exclusive), 490, y + 6, { align: 'right', width: 50 });
      y += rowH;
    });

    // Totals
    y += 5;
    drawHRule(doc, y);
    y += 8;

    const subtotal   = invoice.subtotal || lines.reduce((s, l) => s + (l.amount || l.exclusive || 0), 0);
    const vatAmount  = invoice.vat_amount || 0;
    const total      = invoice.total || subtotal + vatAmount;

    [['Subtotal (excl. VAT)', subtotal], ['VAT @ 16%', vatAmount]].forEach(([label, amount]) => {
      doc.font('Helvetica').fontSize(9).fillColor(DKGREY)
        .text(label, 350, y)
        .text(kes(amount), 0, y, { align: 'right', width: 540 });
      y += 16;
    });

    doc.rect(50, y, 495, 28).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(12).fillColor(GOLD)
      .text('TOTAL DUE', 65, y + 8)
      .text(kes(total), 0, y + 8, { align: 'right', width: 540 });
    y += 36;

    // KRA eTIMS info
    doc.rect(50, y, 495, 32).fillColor('#F0F9F4').fill().rect(50, y, 495, 32).strokeColor('#86EFAC').lineWidth(0.5).stroke();
    doc.font('Helvetica-Bold').fontSize(8).fillColor(GREEN).text('KRA eTIMS', 65, y + 8);
    doc.font('Helvetica').fontSize(7.5).fillColor(DKGREY)
      .text(`CU Invoice No: ${invoice.etims_cu_no || 'Pending submission'}`, 65, y + 20)
      .text(`QSL KRA PIN: ${_company.kra_pin}`, 280, y + 20);
    y += 40;

    // Payment details
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('PAYMENT INSTRUCTIONS', 50, y);
    y += 12;
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text('Bank Transfer: Equity Bank Kenya · A/C: [Account Number] · Branch: [Branch]', 50, y)
      .text(`M-PESA Paybill: ${process.env.MPESA_SHORTCODE || '[Paybill]'} · Account: ${invoice.invoice_no}`, 50, y + 12);

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/invoices/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── CALIBRATION CERTIFICATE PDF ───────────────────────────────────────────────

async function generateCalibrationCert(cert, client, technician, refStandard) {
  const dir  = path.join(UPLOAD_DIR, 'certificates');
  ensureDir(dir);
  const file = path.join(dir, `cert_${cert.cert_no.replace(/\//g,'_')}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    // ISO 17025 header
    let y = 50;
    doc.rect(0, 0, 595, 90).fill(NAVY);
    doc.rect(0, 90, 595, 4).fill(GOLD);

    doc.font('Helvetica-Bold').fontSize(20).fillColor(GOLD).text('QSL', 50, 20);
    doc.font('Helvetica').fontSize(8).fillColor('#aabbcc').text('QALIBRATED SYSTEMS LIMITED', 50, 44);
    doc.font('Helvetica').fontSize(7).fillColor('#8899aa')
      .text('ISO/IEC 17025:2017 Accredited Calibration Laboratory', 50, 56)
      .text('Accreditation No: [KEBS/KENAS Accreditation Number]', 50, 66);

    doc.font('Helvetica-Bold').fontSize(16).fillColor('#ffffff').text('CALIBRATION CERTIFICATE', 0, 28, { align: 'right', width: 545 });
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD).text(cert.cert_no, 0, 50, { align: 'right', width: 545 });

    y = 106;

    // Certificate details grid
    const details = [
      ['Client', client?.name || '—'],
      ['Client Address', client?.address || '—'],
      ['Instrument Description', cert.instrument],
      ['Manufacturer / Make', cert.make || '—'],
      ['Model', cert.model || '—'],
      ['Serial Number', cert.serial_no || '—'],
      ['Measurement Range', cert.range || '—'],
      ['Date of Calibration', dateStr(cert.calibrated_at)],
      ['Next Calibration Date', dateStr(cert.next_cal_date)],
      ['Technician', technician?.first_name ? `${technician.first_name} ${technician.last_name}` : '—'],
    ];

    details.forEach(([label, value], i) => {
      const rowY = y + i * 22;
      if (i % 2 === 0) doc.rect(50, rowY, 495, 22).fillColor('#F8FAFC').fill();
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor(NAVY).text(label, 65, rowY + 7);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(value, 250, rowY + 7, { width: 280 });
    });

    y += details.length * 22 + 10;

    // Environmental conditions
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text('ENVIRONMENTAL CONDITIONS DURING CALIBRATION', 65, y + 5);
    y += 18;
    doc.rect(50, y, 495, 22).fillColor('#F0F4F8').fill();
    doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
      .text(`Temperature: ${cert.temp_c || '—'} °C`, 65, y + 7)
      .text(`Relative Humidity: ${cert.humidity_pct || '—'} %`, 220, y + 7)
      .text('Controlled laboratory conditions', 380, y + 7);
    y += 30;

    // Reference standard
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text('REFERENCE STANDARD USED', 65, y + 5);
    y += 18;
    doc.rect(50, y, 495, 22).fillColor('#F0F4F8').fill();
    doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY)
      .text(`Standard: ${refStandard?.name || '—'}`, 65, y + 7)
      .text(`Traceable to: ${refStandard?.traceable_to || 'KEBS'} → BIPM`, 280, y + 7);
    y += 30;

    // Uncertainty
    doc.rect(50, y, 495, 18).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text('MEASUREMENT UNCERTAINTY', 65, y + 5);
    y += 18;
    doc.rect(50, y, 495, 35).fillColor('#FFFBEB').fill().rect(50, y, 495, 35).strokeColor('#FCD34D').lineWidth(0.5).stroke();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(DKGREY).text(`Expanded Uncertainty: ${cert.uncertainty || '—'}`, 65, y + 8);
    doc.font('Helvetica').fontSize(7.5).fillColor(GREY).text('Coverage factor k = 2, confidence level ≈ 95.45%. Evaluated per ISO/IEC Guide 98-3:2008 (GUM).', 65, y + 24);
    y += 43;

    // Result
    const passed = cert.result === 'pass' || cert.result === 'adjusted';
    doc.rect(50, y, 495, 32).fillColor(passed ? '#F0FFF4' : '#FFF0F0').fill()
       .rect(50, y, 495, 32).strokeColor(passed ? '#86EFAC' : '#FCA5A5').lineWidth(1).stroke();
    doc.font('Helvetica-Bold').fontSize(12).fillColor(passed ? GREEN : RED)
      .text(passed ? '✓  CALIBRATION RESULT: PASS' : '✗  CALIBRATION RESULT: FAIL', 65, y + 10);
    y += 40;

    // Digital signature
    const sigData = cert.tech_sig ? (typeof cert.tech_sig === 'string' ? JSON.parse(cert.tech_sig) : cert.tech_sig) : null;
    doc.rect(50, y, 495, 45).fillColor('#F0F4F8').fill().rect(50, y, 495, 45).strokeColor(LGREY).lineWidth(0.5).stroke();
    doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY).text('AUTHORISED BY — DIGITAL SIGNATURE (ARCH-007B)', 65, y + 8);
    doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
      .text(`Technician: ${technician?.first_name ? `${technician.first_name} ${technician.last_name}` : '—'}`, 65, y + 20)
      .text(`Signature Key: ${sigData?.key_id || 'QSL-DS-DM-2024'}`, 65, y + 32);
    doc.font('Helvetica').fontSize(7).fillColor(GREEN)
      .text(`RSA-2048 Digital Signature: ${sigData?.signature ? sigData.signature.slice(0,40) + '...' : 'Applied'}`, 250, y + 20);
    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text(`Timestamp: ${sigData?.timestamp || dateStr(cert.calibrated_at)}`, 250, y + 32);
    y += 55;

    // Disclaimer
    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text('This certificate relates only to the item(s) submitted for calibration. Results are not valid outside the stated range. This certificate shall not be reproduced except in full without written approval from QSL.', 50, y, { width: 495, align: 'justify' });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/certificates/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── AGED DEBTORS REPORT PDF ───────────────────────────────────────────────────

async function generateAgedDebtorsReport(clients, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().split('T')[0];
  const file = path.join(dir, `aged_debtors_${date}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, 'AGED DEBTORS REPORT', `Generated: ${dateStr(new Date())} by ${generatedBy}`);

    let y = 110;
    const total = clients.reduce((s, c) => s + (c.outstanding || 0), 0);

    // Summary box
    doc.rect(50, y, 745, 35).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD)
      .text(`Total Outstanding: ${kes(total)}`, 65, y + 12)
      .text(`${clients.length} Clients`, 0, y + 12, { align: 'right', width: 790 });
    y += 45;

    // Table header
    const cols = [65, 280, 390, 470, 560, 680];
    const headers = ['Client Name', 'Contact', 'Account Owner', 'Outstanding (Kshs)', 'Credit Limit', 'Status'];
    doc.rect(50, y, 745, 20).fillColor('#334155').fill();
    headers.forEach((h, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6);
    });
    y += 20;

    clients.forEach((c, i) => {
      const rowH = 18;
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#F8FAFC').fill();
      doc.font('Helvetica').fontSize(8).fillColor(DKGREY)
        .text(c.name, cols[0], y + 5, { width: 210 })
        .text(c.contact_person || '—', cols[1], y + 5, { width: 105 })
        .text(c.account_owner || '—', cols[2], y + 5, { width: 75 })
        .text(kes(c.outstanding), cols[3], y + 5, { width: 85 })
        .text(kes(c.credit_limit || 0), cols[4], y + 5, { width: 115 });
      doc.font('Helvetica-Bold').fontSize(8).fillColor(c.outstanding > 0 ? RED : GREEN)
        .text(c.outstanding > 0 ? 'OUTSTANDING' : 'CLEARED', cols[5], y + 5);
      y += rowH;

      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
      }
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── AUDIT TRAIL EXPORT PDF ────────────────────────────────────────────────────

async function generateAuditTrail(entries, filters, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const file = path.join(dir, `audit_trail_${date}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, 'AUDIT TRAIL EXPORT', `Generated: ${dateStr(new Date())} · ${entries.length} records · By: ${generatedBy}`);

    let y = 110;
    if (filters) {
      doc.font('Helvetica').fontSize(8).fillColor(GREY)
        .text(`Filters — Module: ${filters.module || 'All'} | User: ${filters.user || 'All'} | Date: ${filters.from || '—'} to ${filters.to || '—'}`, 50, y);
      y += 20;
    }

    const cols = [50, 165, 255, 340, 440, 560];
    const headers = ['Timestamp', 'User', 'Module', 'Action', 'Record ID', 'Details'];
    doc.rect(50, y, 745, 20).fillColor(NAVY).fill();
    headers.forEach((h, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6);
    });
    y += 20;

    entries.forEach((e, i) => {
      const rowH = 16;
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#FAFAFA').fill();
      doc.font('Helvetica').fontSize(7).fillColor(DKGREY)
        .text(new Date(e.created_at).toLocaleString('en-KE'), cols[0], y + 4, { width: 110 })
        .text(e.user_name || '—', cols[1], y + 4, { width: 85 })
        .text(e.module, cols[2], y + 4, { width: 80 })
        .text(e.action, cols[3], y + 4, { width: 95 })
        .text(e.record_id ? e.record_id.slice(0, 12) + '…' : '—', cols[4], y + 4, { width: 115 })
        .text(e.new_value ? JSON.stringify(e.new_value).slice(0, 40) : '', cols[5], y + 4, { width: 185 });
      y += rowH;

      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
        // Re-draw header on new page
        doc.rect(50, y, 745, 20).fillColor(NAVY).fill();
        headers.forEach((h, i) => doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(h, cols[i], y + 6));
        y += 20;
      }
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── PROFIT & LOSS STATEMENT PDF ───────────────────────────────────────────────

async function generateProfitAndLoss(plData, period, generatedBy) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const file = path.join(dir, `pnl_${period.replace(/[\s\/]/g,'_')}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    let y = addHeader(doc, 'PROFIT & LOSS STATEMENT', `Period: ${period}`);
    y = 110;

    doc.font('Helvetica').fontSize(8).fillColor(GREY)
      .text(`Generated: ${dateStr(new Date())} by ${generatedBy} · All figures in Kenya Shillings (Kshs)`, 50, y);
    y += 18;

    const section = (label, rows, total, totalColor = NAVY, fillHeader = NAVY) => {
      doc.rect(50, y, 495, 18).fillColor(fillHeader).fill();
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#ffffff').text(label, 65, y + 5);
      y += 18;
      rows.forEach((r, i) => {
        if (i % 2 === 0) doc.rect(50, y, 495, 16).fillColor('#F8FAFC').fill();
        doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(r.name, 65, y + 4, { width: 350 });
        doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text(kes(r.amount), 0, y + 4, { align: 'right', width: 530 });
        y += 16;
      });
      doc.rect(50, y, 495, 20).fillColor('#F0F4F8').fill();
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(totalColor).text(`Total ${label}`, 65, y + 5);
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(totalColor).text(kes(total), 0, y + 5, { align: 'right', width: 530 });
      y += 28;
    };

    if (!plData.has_gl_data) {
      doc.rect(50, y, 495, 50).fillColor('#FFFBEB').fill().rect(50, y, 495, 50).strokeColor('#FCD34D').lineWidth(0.5).stroke();
      doc.font('Helvetica-Bold').fontSize(10).fillColor(AMBER).text('No General Ledger postings found for this period.', 65, y + 12);
      doc.font('Helvetica').fontSize(8.5).fillColor(DKGREY).text('Post journal entries via Finance → Journal Entries for figures to appear here. This statement will populate automatically once postings exist.', 65, y + 28, { width: 460 });
      y += 60;
    }

    section('Revenue', plData.revenue, plData.totalRevenue, GREEN, NAVY);
    section('Cost of Sales', plData.cogs, plData.totalCOGS, RED, NAVY);

    doc.rect(50, y, 495, 24).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD).text('GROSS PROFIT', 65, y + 7);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD).text(kes(plData.grossProfit), 0, y + 7, { align: 'right', width: 530 });
    doc.font('Helvetica').fontSize(7).fillColor('#C8D4DE').text(`Margin: ${plData.totalRevenue ? ((plData.grossProfit/plData.totalRevenue)*100).toFixed(1) : '0.0'}%`, 65, y + 17);
    y += 34;

    section('Operating Expenses', plData.opex, plData.totalOpex, RED, NAVY);
    section('Depreciation & Amortisation', plData.depreciation, plData.totalDepreciation, RED, NAVY);

    doc.rect(50, y, 495, 24).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD).text('OPERATING PROFIT (EBIT)', 65, y + 7);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD).text(kes(plData.operatingProfit), 0, y + 7, { align: 'right', width: 530 });
    y += 34;

    if (plData.otherIncome.length || plData.financeCosts.length) {
      section('Other Income', plData.otherIncome, plData.totalOtherIncome, GREEN, NAVY);
      section('Finance Costs', plData.financeCosts, plData.totalFinanceCosts, RED, NAVY);
    }

    doc.rect(50, y, 495, 36).fillColor(plData.netProfit >= 0 ? GREEN : RED).fill();
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#ffffff').text('NET PROFIT / (LOSS)', 65, y + 11);
    doc.font('Helvetica-Bold').fontSize(15).fillColor('#ffffff').text(kes(plData.netProfit), 0, y + 10, { align: 'right', width: 530 });
    y += 46;

    doc.font('Helvetica').fontSize(7).fillColor(GREY)
      .text('Prepared in accordance with the QSL Chart of Accounts (ICPAK-aligned). This statement is system-generated from posted General Ledger journal entries.', 50, y, { width: 495 });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

// ── GENERIC TABULAR REPORT PDF (point 4 — Reporting exports) ─────────────────
// Shared by Inventory, Requisitions, Vehicles, and User Activity reports so
// each doesn't need its own near-identical layout function. Caller supplies
// the title, column definitions, rows, and an optional filter summary line.

async function generateTabularReport({ title, subtitle, filtersSummary, columns, rows, generatedBy, filenamePrefix }) {
  const dir  = path.join(UPLOAD_DIR, 'reports');
  ensureDir(dir);
  const date = new Date().toISOString().split('T')[0];
  const file = path.join(dir, `${filenamePrefix || 'report'}_${date}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'landscape' });
    const ws  = fs.createWriteStream(file);
    doc.pipe(ws);

    addHeader(doc, title, subtitle || `Generated: ${dateStr(new Date())} by ${generatedBy}`);

    let y = 110;

    if (filtersSummary) {
      doc.font('Helvetica').fontSize(8).fillColor(GREY).text(`Filters: ${filtersSummary}`, 50, y);
      y += 16;
    }

    doc.rect(50, y, 745, 26).fillColor(NAVY).fill();
    doc.font('Helvetica-Bold').fontSize(10).fillColor(GOLD)
      .text(`${rows.length} record(s)`, 65, y + 8);
    y += 36;

    // Compute column widths proportionally across the 745pt usable width
    const totalWeight = columns.reduce((s, c) => s + (c.weight || 1), 0);
    const usableWidth  = 745;
    let cursorX = 50;
    const colX = [];
    columns.forEach(c => {
      colX.push(cursorX);
      cursorX += (usableWidth * (c.weight || 1)) / totalWeight;
    });

    doc.rect(50, y, 745, 20).fillColor('#334155').fill();
    columns.forEach((c, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff').text(c.label, colX[i] + 5, y + 6, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8 });
    });
    y += 20;

    rows.forEach((row, i) => {
      const rowH = 18;
      if (y > doc.page.height - 80) {
        doc.addPage({ layout: 'landscape' });
        y = 50;
      }
      if (i % 2 === 0) doc.rect(50, y, 745, rowH).fillColor('#F8FAFC').fill();
      columns.forEach((c, ci) => {
        const val = c.format ? c.format(row[c.key], row) : (row[c.key] ?? '—');
        doc.font('Helvetica').fontSize(8).fillColor(c.color ? c.color(row[c.key], row) : DKGREY)
          .text(String(val), colX[ci] + 5, y + 5, { width: (usableWidth * (c.weight || 1)) / totalWeight - 8 });
      });
      y += rowH;
    });

    addFooter(doc);
    doc.end();

    ws.on('finish', () => resolve({ path: file, url: `/uploads/reports/${path.basename(file)}` }));
    ws.on('error', reject);
  });
}

module.exports = {
  loadCompany,
  generatePayslip,
  generateInvoice,
  generateCalibrationCert,
  generateAgedDebtorsReport,
  generateAuditTrail,
  generateProfitAndLoss,
  generateTabularReport,
};
