-- database/pg-schema.sql — Generated PostgreSQL schema
-- AUTO-GENERATED by database/generate-pg-schema.js — do not hand-edit.
-- Regenerate after any schema change in database/init.js or any migrate-*.js
-- by running: node database/generate-pg-schema.js
-- Generated: 2026-06-19T13:21:15.432Z
-- Source: live qsl_erp.db (80 tables, 12 indexes)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE assets (
  id              TEXT PRIMARY KEY,
  tag_no          TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  description     TEXT,
  category        TEXT NOT NULL,
  serial_no       TEXT,
  purchase_date   TEXT NOT NULL,
  cost            NUMERIC(15,2) NOT NULL,
  dep_method      TEXT DEFAULT 'straight_line',
  dep_rate        NUMERIC(15,2) DEFAULT 0.20,
  useful_life     INTEGER DEFAULT 5,
  residual_value  NUMERIC(15,2) DEFAULT 0,
  nbv             NUMERIC(15,2) NOT NULL,
  location        TEXT,
  custodian       TEXT REFERENCES employees(id),
  supplier_id     TEXT REFERENCES suppliers(id),
  warranty_to     TEXT,
  insurance_to    TEXT,
  status          TEXT DEFAULT 'in_use',
  disposal_date   TEXT,
  disposal_amount NUMERIC(15,2),
  disposal_reason TEXT,
  disposal_sig    TEXT,
  grn_id          TEXT REFERENCES grns(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE attendance (
  id            TEXT PRIMARY KEY,
  employee_id   TEXT REFERENCES employees(id),
  date          TEXT NOT NULL,
  clock_in      TEXT,
  clock_out     TEXT,
  location_lat  NUMERIC(15,2),
  location_lng  NUMERIC(15,2),
  location_name TEXT,
  hours_worked  NUMERIC(15,2),
  is_late       INTEGER DEFAULT 0,
  notes         TEXT
);

CREATE TABLE audit_log (
  id          TEXT PRIMARY KEY,
  user_id     TEXT,
  user_name   TEXT,
  action      TEXT NOT NULL,
  module      TEXT NOT NULL,
  record_id   TEXT,
  record_type TEXT,
  old_value   TEXT,
  new_value   TEXT,
  ip_address  TEXT,
  user_agent  TEXT,
  sig_used    TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE bank_accounts (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  bank        TEXT NOT NULL,
  account_no  TEXT UNIQUE NOT NULL,
  branch      TEXT,
  currency    TEXT DEFAULT 'KES',
  balance     NUMERIC(15,2) DEFAULT 0,
  is_active   INTEGER DEFAULT 1,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE bid_compliance (
  id              TEXT PRIMARY KEY,
  bid_id          TEXT REFERENCES bids(id),
  requirement     TEXT NOT NULL,
  type            TEXT NOT NULL,
  position        TEXT DEFAULT 'PENDING',
  evidence_doc    TEXT,
  notes           TEXT,
  checked_by      TEXT REFERENCES employees(id),
  checked_at      TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE bids (
  id                TEXT PRIMARY KEY,
  ref_no            TEXT UNIQUE NOT NULL,
  name              TEXT NOT NULL,
  client            TEXT,
  client_id         TEXT REFERENCES clients(id),
  value             NUMERIC(15,2) DEFAULT 0,
  stage             TEXT DEFAULT 'stage_1',
  deadline          TEXT,
  owner             TEXT REFERENCES employees(id),
  stage2b_status    TEXT DEFAULT 'pending',
  suitability_score NUMERIC(15,2),
  compliance_clear  INTEGER DEFAULT 0,
  stopped           INTEGER DEFAULT 0,
  stopped_reason    TEXT,
  won_lost          TEXT,
  bid_bond_ref      TEXT,
  bid_bond_expiry   TEXT,
  submitted_at      TEXT,
  outcome_date      TEXT,
  created_at        TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE branches (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  address       TEXT,
  city          TEXT,
  country       TEXT DEFAULT 'Kenya',
  manager_id    TEXT REFERENCES employees(id),
  is_active     INTEGER DEFAULT 1,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE calibration_certs (
  id              TEXT PRIMARY KEY,
  cert_no         TEXT UNIQUE NOT NULL,
  job_id          TEXT REFERENCES calibration_jobs(id),
  client_id       TEXT REFERENCES clients(id),
  instrument      TEXT NOT NULL,
  make            TEXT,
  model           TEXT,
  serial_no       TEXT,
  range           TEXT,
  uncertainty     TEXT,
  ref_standard_id TEXT,
  calibrated_at   TEXT NOT NULL,
  next_cal_date   TEXT,
  result          TEXT DEFAULT 'pass',
  temp_c          NUMERIC(15,2),
  humidity_pct    NUMERIC(15,2),
  technician_id   TEXT REFERENCES employees(id),
  tech_sig        TEXT,
  cert_path       TEXT,
  etims_ref       TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE calibration_jobs (
  id              TEXT PRIMARY KEY,
  job_no          TEXT UNIQUE NOT NULL,
  client_id       TEXT REFERENCES clients(id),
  site            TEXT,
  instruments     TEXT,
  scheduled_date  TEXT,
  technician_id   TEXT REFERENCES employees(id),
  status          TEXT DEFAULT 'scheduled',
  project_id      TEXT REFERENCES projects(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE chart_of_accounts (
  id          TEXT PRIMARY KEY,
  code        TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  category    TEXT NOT NULL,
  type        TEXT NOT NULL,
  parent_id   TEXT REFERENCES chart_of_accounts(id),
  is_active   INTEGER DEFAULT 1,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE client_transfers (
  id              TEXT PRIMARY KEY,
  client_id       TEXT REFERENCES clients(id),
  from_owner      TEXT REFERENCES employees(id),
  to_owner        TEXT REFERENCES employees(id),
  reason          TEXT NOT NULL,
  doc_path        TEXT,
  cfo_sig         TEXT,
  cfo_signed_at   TEXT,
  md_sig          TEXT,
  md_signed_at    TEXT,
  status          TEXT DEFAULT 'pending',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE clients (
  id              TEXT PRIMARY KEY,
  code            TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  contact_person  TEXT,
  email           TEXT,
  phone           TEXT,
  address         TEXT,
  kra_pin         TEXT,
  segment         TEXT,
  account_owner   TEXT REFERENCES employees(id),
  introduced_by   TEXT REFERENCES employees(id),
  outstanding     NUMERIC(15,2) DEFAULT 0,
  credit_limit    NUMERIC(15,2) DEFAULT 0,
  payment_terms   INTEGER DEFAULT 30,
  status          TEXT DEFAULT 'active',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
, company_id TEXT REFERENCES companies(id));

CREATE TABLE companies (
  id              TEXT PRIMARY KEY,
  code            TEXT UNIQUE NOT NULL,
  legal_name      TEXT NOT NULL,
  kra_pin         TEXT,
  registered_address TEXT,
  bank_account_id TEXT REFERENCES bank_accounts(id),
  is_primary      INTEGER DEFAULT 0,
  related_party_id TEXT REFERENCES related_parties(id),
  status          TEXT DEFAULT 'active',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE compliance_docs (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL,
  issuer      TEXT,
  ref_no      TEXT,
  issued_at   TEXT,
  expires_at  TEXT,
  responsible TEXT REFERENCES employees(id),
  doc_path    TEXT,
  status      TEXT DEFAULT 'current',
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE daily_project_updates (
  id              TEXT PRIMARY KEY,
  project_id      TEXT REFERENCES projects(id),
  date            TEXT NOT NULL,
  exp_update      TEXT,
  milestone_update TEXT,
  updated_by      TEXT REFERENCES employees(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE debtor_followups (
    id TEXT PRIMARY KEY,
    client_id TEXT REFERENCES clients(id),
    followup_date TEXT NOT NULL,
    status TEXT NOT NULL,
    note TEXT,
    next_followup_date TEXT,
    recorded_by TEXT REFERENCES employees(id),
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
    UNIQUE(client_id, followup_date)
  );

CREATE TABLE departments (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  branch_id     TEXT REFERENCES branches(id),
  head_id       TEXT REFERENCES employees(id),
  is_active     INTEGER DEFAULT 1,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE depreciation_runs (
  id          TEXT PRIMARY KEY,
  period      TEXT NOT NULL,
  asset_id    TEXT REFERENCES assets(id),
  nbv_before  NUMERIC(15,2) NOT NULL,
  charge      NUMERIC(15,2) NOT NULL,
  nbv_after   NUMERIC(15,2) NOT NULL,
  method      TEXT,
  run_by      TEXT REFERENCES employees(id),
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE digital_signatures (
  id          TEXT PRIMARY KEY,
  user_id     TEXT REFERENCES users(id),
  key_id      TEXT UNIQUE NOT NULL,
  public_key  TEXT NOT NULL,
  private_key TEXT NOT NULL,
  algorithm   TEXT DEFAULT 'RSA-2048',
  is_active   INTEGER DEFAULT 1,
  issued_at   TEXT DEFAULT (CURRENT_TIMESTAMP),
  revoked_at  TEXT,
  revoked_by  TEXT,
  uses        INTEGER DEFAULT 0
);

CREATE TABLE employees (
  id                TEXT PRIMARY KEY,
  emp_no            TEXT UNIQUE NOT NULL,
  first_name        TEXT NOT NULL,
  last_name         TEXT NOT NULL,
  email             TEXT UNIQUE NOT NULL,
  phone             TEXT,
  id_number         TEXT UNIQUE,
  kra_pin           TEXT,
  nhif_no           TEXT,
  nssf_no           TEXT,
  department        TEXT NOT NULL,
  role              TEXT NOT NULL,
  grade             TEXT,
  reporting_to      TEXT REFERENCES employees(id),
  employment_type   TEXT DEFAULT 'permanent',
  date_joined       TEXT NOT NULL,
  date_left         TEXT,
  status            TEXT DEFAULT 'active',
  basic_salary      NUMERIC(15,2) NOT NULL DEFAULT 0,
  bank_name         TEXT,
  bank_account      TEXT,
  bank_branch       TEXT,
  address           TEXT,
  emergency_contact TEXT,
  emergency_phone   TEXT,
  leave_balance     INTEGER DEFAULT 21,
  l_and_d_hours     NUMERIC(15,2) DEFAULT 0,
  l_and_d_target    NUMERIC(15,2) DEFAULT 40,
  created_at        TEXT DEFAULT (CURRENT_TIMESTAMP),
  updated_at        TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE eod_debtor_reports (
    id TEXT PRIMARY KEY,
    report_date TEXT UNIQUE NOT NULL,
    submitted_by TEXT REFERENCES employees(id),
    submitted_at TEXT,
    status TEXT DEFAULT 'pending',
    reminder_sent_at TEXT,
    escalated_at TEXT,
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP)
  );

CREATE TABLE grns (
  id                TEXT PRIMARY KEY,
  grn_no            TEXT UNIQUE NOT NULL,
  lpo_id            TEXT REFERENCES lpos(id),
  date              TEXT NOT NULL,
  received_by       TEXT REFERENCES employees(id),
  stage1_done       INTEGER DEFAULT 0,
  stage1_signed_at  TEXT,
  stage1_notes      TEXT,
  photo_paths       TEXT,
  stage2_done       INTEGER DEFAULT 0,
  stage2_raised_at  TEXT,
  discrepancies     TEXT,
  status            TEXT DEFAULT 'pending',
  created_at        TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE ic_transactions (
  id              TEXT PRIMARY KEY,
  entity_id       TEXT REFERENCES related_parties(id),
  type            TEXT NOT NULL,
  contract_value  NUMERIC(15,2) DEFAULT 0,
  fee_amount      NUMERIC(15,2) DEFAULT 0,
  fee_pct         NUMERIC(15,2) DEFAULT 0,
  min_fee_pct     NUMERIC(15,2) DEFAULT 0.05,
  collected       NUMERIC(15,2) DEFAULT 0,
  status          TEXT DEFAULT 'pending',
  icsa_verified   INTEGER DEFAULT 0,
  invoice_ref     TEXT,
  notes           TEXT,
  created_by      TEXT REFERENCES employees(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
, project_id TEXT REFERENCES projects(id));

CREATE TABLE imprest (
  id              TEXT PRIMARY KEY,
  ref_no          TEXT UNIQUE NOT NULL,
  employee_id     TEXT REFERENCES employees(id),
  amount          NUMERIC(15,2) NOT NULL,
  purpose         TEXT NOT NULL,
  date_issued     TEXT NOT NULL,
  due_date        TEXT NOT NULL,
  status          TEXT DEFAULT 'pending',
  approved_by     TEXT REFERENCES employees(id),
  approved_at     TEXT,
  receipt_path    TEXT,
  receipt_verified INTEGER DEFAULT 0,
  amount_accounted NUMERIC(15,2) DEFAULT 0,
  converted_at    TEXT,
  converted_to_advance INTEGER DEFAULT 0,
  notes           TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE integration_logs (
  id          TEXT PRIMARY KEY,
  service     TEXT NOT NULL,
  direction   TEXT NOT NULL,
  endpoint    TEXT,
  request     TEXT,
  response    TEXT,
  status_code INTEGER,
  success     INTEGER DEFAULT 0,
  error       TEXT,
  ref_id      TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE interactions (
  id          TEXT PRIMARY KEY,
  client_id   TEXT REFERENCES clients(id),
  lead_id     TEXT REFERENCES leads(id),
  type        TEXT NOT NULL,
  date        TEXT NOT NULL,
  summary     TEXT NOT NULL,
  next_action TEXT,
  done_by     TEXT REFERENCES employees(id),
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE item_categories (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  parent_id     TEXT REFERENCES item_categories(id),
  description   TEXT,
  is_active     INTEGER DEFAULT 1,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE items (
  id              TEXT PRIMARY KEY,
  code            TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  description     TEXT,
  category        TEXT NOT NULL,
  unit            TEXT DEFAULT 'each',
  reorder_level   INTEGER DEFAULT 0,
  reorder_qty     INTEGER DEFAULT 0,
  unit_cost       NUMERIC(15,2) DEFAULT 0,
  msp             NUMERIC(15,2) DEFAULT 0,
  location        TEXT,
  supplier_id     TEXT REFERENCES suppliers(id),
  warranty_months INTEGER DEFAULT 0,
  is_serialised   INTEGER DEFAULT 0,
  is_active       INTEGER DEFAULT 1,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
, category_id TEXT REFERENCES item_categories(id));

CREATE TABLE journal_entries (
  id              TEXT PRIMARY KEY,
  entry_no        TEXT UNIQUE NOT NULL,
  date            TEXT NOT NULL,
  description     TEXT NOT NULL,
  reference       TEXT,
  module          TEXT,
  module_ref      TEXT,
  status          TEXT DEFAULT 'draft',
  prepared_by     TEXT REFERENCES employees(id),
  reviewed_by     TEXT REFERENCES employees(id),
  approved_by     TEXT REFERENCES employees(id),
  approved_sig    TEXT,
  approved_at     TEXT,
  is_reversal     INTEGER DEFAULT 0,
  reversed_by     TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE journal_lines (
  id          TEXT PRIMARY KEY,
  entry_id    TEXT REFERENCES journal_entries(id),
  account_id  TEXT REFERENCES chart_of_accounts(id),
  description TEXT,
  debit       NUMERIC(15,2) DEFAULT 0,
  credit      NUMERIC(15,2) DEFAULT 0,
  dept        TEXT,
  project_id  TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE kpi_scorecards (
  id              TEXT PRIMARY KEY,
  employee_id     TEXT REFERENCES employees(id),
  period          TEXT NOT NULL,
  dimension       TEXT NOT NULL,
  weight          NUMERIC(15,2) NOT NULL,
  score           NUMERIC(15,2),
  target          TEXT,
  notes           TEXT,
  reviewed_by     TEXT REFERENCES employees(id),
  reviewed_at     TEXT,
  increment_blocked INTEGER DEFAULT 0,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE l_and_d (
  id            TEXT PRIMARY KEY,
  employee_id   TEXT REFERENCES employees(id),
  course_name   TEXT NOT NULL,
  provider      TEXT,
  hours         NUMERIC(15,2) NOT NULL,
  date          TEXT NOT NULL,
  certificate   TEXT,
  cost          NUMERIC(15,2) DEFAULT 0,
  approved_by   TEXT REFERENCES employees(id),
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE leads (
  id              TEXT PRIMARY KEY,
  ref_no          TEXT UNIQUE NOT NULL,
  company         TEXT NOT NULL,
  contact_name    TEXT,
  email           TEXT,
  phone           TEXT,
  service         TEXT,
  estimated_value NUMERIC(15,2) DEFAULT 0,
  stage           TEXT DEFAULT 'lead',
  source          TEXT,
  owner           TEXT REFERENCES employees(id),
  won_lost        TEXT,
  won_lost_reason TEXT,
  won_at          TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE leave_requests (
  id            TEXT PRIMARY KEY,
  employee_id   TEXT REFERENCES employees(id),
  leave_type    TEXT NOT NULL,
  start_date    TEXT NOT NULL,
  end_date      TEXT NOT NULL,
  days          INTEGER NOT NULL,
  reason        TEXT,
  status        TEXT DEFAULT 'pending',
  approved_by   TEXT REFERENCES employees(id),
  approved_at   TEXT,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE low_stock_alerts (
  id            TEXT PRIMARY KEY,
  item_id       TEXT REFERENCES items(id),
  location_id   TEXT REFERENCES store_locations(id),
  current_qty   NUMERIC(15,2) NOT NULL,
  reorder_level NUMERIC(15,2) NOT NULL,
  status        TEXT DEFAULT 'open',
  acknowledged_by TEXT REFERENCES employees(id),
  acknowledged_at TEXT,
  notified_at   TEXT,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE lpo_lines (
  id          TEXT PRIMARY KEY,
  lpo_id      TEXT REFERENCES lpos(id),
  item_code   TEXT,
  description TEXT NOT NULL,
  quantity    NUMERIC(15,2) NOT NULL,
  unit        TEXT,
  unit_price  NUMERIC(15,2) NOT NULL,
  total       NUMERIC(15,2) NOT NULL,
  vat_rate    NUMERIC(15,2) DEFAULT 0.16
);

CREATE TABLE lpos (
  id              TEXT PRIMARY KEY,
  lpo_no          TEXT UNIQUE NOT NULL,
  pr_id           TEXT REFERENCES purchase_requisitions(id),
  supplier_id     TEXT REFERENCES suppliers(id),
  date            TEXT NOT NULL,
  delivery_date   TEXT,
  total           NUMERIC(15,2) NOT NULL,
  vat             NUMERIC(15,2) DEFAULT 0,
  grand_total     NUMERIC(15,2) NOT NULL,
  status          TEXT DEFAULT 'issued',
  fm_sig          TEXT,
  md_sig          TEXT,
  delivery_terms  TEXT,
  notes           TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE module_flags (
  module_id     TEXT PRIMARY KEY,
  enabled       INTEGER DEFAULT 1,
  display_name  TEXT NOT NULL,
  description   TEXT,
  is_core       INTEGER DEFAULT 0,
  updated_by    TEXT REFERENCES employees(id),
  updated_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE module_integrations (
  id              TEXT PRIMARY KEY,
  source_module   TEXT NOT NULL,
  target_module   TEXT NOT NULL,
  trigger_event   TEXT NOT NULL,
  enabled         INTEGER DEFAULT 0,
  config          TEXT,
  updated_by      TEXT REFERENCES employees(id),
  updated_at      TEXT DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE(source_module, target_module, trigger_event)
);

CREATE TABLE paye_returns (
  id              TEXT PRIMARY KEY,
  period          TEXT UNIQUE NOT NULL,
  payroll_run_id  TEXT REFERENCES payroll_runs(id),
  total_gross     NUMERIC(15,2) DEFAULT 0,
  total_paye      NUMERIC(15,2) DEFAULT 0,
  status          TEXT DEFAULT 'draft',
  filed_at        TEXT,
  payment_ref     TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE payment_vouchers (
  id              TEXT PRIMARY KEY,
  voucher_no      TEXT UNIQUE NOT NULL,
  date            TEXT NOT NULL,
  payee           TEXT NOT NULL,
  payee_type      TEXT,
  amount          NUMERIC(15,2) NOT NULL,
  currency        TEXT DEFAULT 'KES',
  purpose         TEXT NOT NULL,
  payment_method  TEXT,
  bank_account_id TEXT REFERENCES bank_accounts(id),
  reference       TEXT,
  status          TEXT DEFAULT 'draft',
  auth_level      TEXT DEFAULT 'staff',
  approved_by     TEXT REFERENCES employees(id),
  approved_sig    TEXT,
  approved_at     TEXT,
  module_ref      TEXT,
  withholding_tax NUMERIC(15,2) DEFAULT 0,
  vat_amount      NUMERIC(15,2) DEFAULT 0,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE payroll_entries (
  id              TEXT PRIMARY KEY,
  run_id          TEXT REFERENCES payroll_runs(id),
  employee_id     TEXT REFERENCES employees(id),
  basic_salary    NUMERIC(15,2) NOT NULL,
  allowances      NUMERIC(15,2) DEFAULT 0,
  gross_pay       NUMERIC(15,2) NOT NULL,
  paye            NUMERIC(15,2) DEFAULT 0,
  nhif            NUMERIC(15,2) DEFAULT 0,
  nssf            NUMERIC(15,2) DEFAULT 0,
  housing_levy    NUMERIC(15,2) DEFAULT 0,
  imprest_deduct  NUMERIC(15,2) DEFAULT 0,
  other_deductions NUMERIC(15,2) DEFAULT 0,
  net_pay         NUMERIC(15,2) NOT NULL,
  status          TEXT DEFAULT 'pending',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE payroll_runs (
  id              TEXT PRIMARY KEY,
  period          TEXT UNIQUE NOT NULL,
  status          TEXT DEFAULT 'draft',
  total_gross     NUMERIC(15,2) DEFAULT 0,
  total_paye      NUMERIC(15,2) DEFAULT 0,
  total_nhif      NUMERIC(15,2) DEFAULT 0,
  total_nssf      NUMERIC(15,2) DEFAULT 0,
  total_housing   NUMERIC(15,2) DEFAULT 0,
  total_net       NUMERIC(15,2) DEFAULT 0,
  fm_sig          TEXT,
  fm_signed_at    TEXT,
  cfo_sig         TEXT,
  cfo_signed_at   TEXT,
  md_sig          TEXT,
  md_signed_at    TEXT,
  locked_at       TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE permissions (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  module        TEXT NOT NULL,
  description   TEXT
);

CREATE TABLE policy_docs (
  id          TEXT PRIMARY KEY,
  code        TEXT UNIQUE NOT NULL,
  title       TEXT NOT NULL,
  level       TEXT NOT NULL,
  category    TEXT NOT NULL,
  version     TEXT DEFAULT '1.0',
  owner       TEXT REFERENCES employees(id),
  reviewed_at TEXT,
  next_review TEXT,
  doc_path    TEXT,
  status      TEXT DEFAULT 'current',
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE policy_signoffs (
  id          TEXT PRIMARY KEY,
  policy_id   TEXT REFERENCES policy_docs(id),
  employee_id TEXT REFERENCES employees(id),
  signed_at   TEXT,
  sig_key     TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE project_budgets (
  id          TEXT PRIMARY KEY,
  project_id  TEXT REFERENCES projects(id),
  category    TEXT NOT NULL,
  amount      NUMERIC(15,2) NOT NULL,
  notes       TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE project_expenses (
  id              TEXT PRIMARY KEY,
  project_id      TEXT REFERENCES projects(id),
  date            TEXT NOT NULL,
  description     TEXT NOT NULL,
  category        TEXT NOT NULL,
  amount          NUMERIC(15,2) NOT NULL,
  supplier        TEXT,
  receipt_path    TEXT,
  receipt_verified INTEGER DEFAULT 0,
  posted_by       TEXT REFERENCES employees(id),
  approved_by     TEXT REFERENCES employees(id),
  approved_sig    TEXT,
  approved_at     TEXT,
  lpo_id          TEXT REFERENCES lpos(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE project_handover (
  id                  TEXT PRIMARY KEY,
  project_id          TEXT REFERENCES projects(id),
  outgoing_staff      TEXT REFERENCES employees(id),
  outgoing_sig        TEXT,
  outgoing_signed_at  TEXT,
  incoming_person     TEXT,
  incoming_sig        TEXT,
  incoming_signed_at  TEXT,
  dept_head           TEXT REFERENCES employees(id),
  dept_head_sig       TEXT,
  dept_head_signed_at TEXT,
  md_sig              TEXT,
  md_signed_at        TEXT,
  checklist           TEXT,
  completed           INTEGER DEFAULT 0,
  created_at          TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE project_milestones (
  id              TEXT PRIMARY KEY,
  project_id      TEXT REFERENCES projects(id),
  seq             INTEGER,
  description     TEXT NOT NULL,
  planned_date    TEXT,
  actual_date     TEXT,
  value           NUMERIC(15,2) DEFAULT 0,
  pct_complete    INTEGER DEFAULT 0,
  status          TEXT DEFAULT 'planned',
  updated_by      TEXT REFERENCES employees(id),
  updated_at      TEXT,
  notes           TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE project_subcontractors (
  id              TEXT PRIMARY KEY,
  project_id      TEXT REFERENCES projects(id),
  supplier_id     TEXT REFERENCES suppliers(id),
  scope           TEXT,
  contract_value  NUMERIC(15,2) DEFAULT 0,
  paid_to_date    NUMERIC(15,2) DEFAULT 0,
  retention_pct   NUMERIC(15,2) DEFAULT 0.10,
  rams_uploaded   INTEGER DEFAULT 0,
  status          TEXT DEFAULT 'active',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE projects (
  id              TEXT PRIMARY KEY,
  ref_no          TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  client_id       TEXT REFERENCES clients(id),
  contract_value  NUMERIC(15,2) NOT NULL,
  retention_pct   NUMERIC(15,2) DEFAULT 0,
  vat_rate        NUMERIC(15,2) DEFAULT 0.16,
  start_date      TEXT,
  end_date        TEXT,
  status          TEXT DEFAULT 'active',
  pm_id           TEXT REFERENCES employees(id),
  process_owner   TEXT REFERENCES employees(id),
  department      TEXT,
  site            TEXT,
  scope           TEXT,
  budget_total    NUMERIC(15,2) DEFAULT 0,
  expenses_total  NUMERIC(15,2) DEFAULT 0,
  invoiced_total  NUMERIC(15,2) DEFAULT 0,
  collected_total NUMERIC(15,2) DEFAULT 0,
  budget_blocked  INTEGER DEFAULT 0,
  budget_override_sig TEXT,
  budget_override_by  TEXT REFERENCES employees(id),
  budget_override_at  TEXT,
  handover_done   INTEGER DEFAULT 0,
  rams_uploaded   INTEGER DEFAULT 0,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP),
  updated_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
, company_id TEXT REFERENCES companies(id));

CREATE TABLE purchase_requisitions (
  id              TEXT PRIMARY KEY,
  pr_no           TEXT UNIQUE NOT NULL,
  description     TEXT NOT NULL,
  department      TEXT NOT NULL,
  requested_by    TEXT REFERENCES employees(id),
  amount          NUMERIC(15,2) NOT NULL,
  purpose         TEXT NOT NULL,
  supplier_id     TEXT REFERENCES suppliers(id),
  status          TEXT DEFAULT 'draft',
  dept_approved_by TEXT REFERENCES employees(id),
  dept_approved_at TEXT,
  fm_approved_by  TEXT REFERENCES employees(id),
  fm_approved_at  TEXT,
  md_approved_by  TEXT REFERENCES employees(id),
  md_approved_at  TEXT,
  lpo_id          TEXT,
  date            TEXT DEFAULT (CURRENT_DATE),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE reference_standards (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  make            TEXT,
  model           TEXT,
  serial_no       TEXT,
  traceable_to    TEXT DEFAULT 'KEBS',
  last_cal_date   TEXT,
  next_cal_date   TEXT,
  uncertainty     TEXT,
  status          TEXT DEFAULT 'current',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE related_parties (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL,
  icsa_ref    TEXT,
  icsa_path   TEXT,
  contact     TEXT,
  status      TEXT DEFAULT 'active',
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE requisition_approvals (
  id              TEXT PRIMARY KEY,
  requisition_id  TEXT REFERENCES store_requisitions(id),
  level           TEXT NOT NULL,
  approver_id     TEXT REFERENCES employees(id),
  decision        TEXT NOT NULL,
  comments        TEXT,
  decided_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE role_permissions (
  role_id       TEXT REFERENCES roles(id),
  permission_id TEXT REFERENCES permissions(id),
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE roles (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  description   TEXT,
  is_system     INTEGER DEFAULT 0,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE serialised_items (
  id            TEXT PRIMARY KEY,
  item_id       TEXT REFERENCES items(id),
  serial_no     TEXT UNIQUE NOT NULL,
  status        TEXT DEFAULT 'in_stock',
  grn_id        TEXT REFERENCES grns(id),
  client_id     TEXT,
  sale_date     TEXT,
  invoice_no    TEXT,
  warranty_from TEXT,
  warranty_to   TEXT,
  assigned_tech TEXT REFERENCES employees(id),
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE statutory_calendar (
  id              TEXT PRIMARY KEY,
  obligation      TEXT NOT NULL,
  description     TEXT,
  due_day         INTEGER,
  frequency       TEXT,
  next_due        TEXT,
  responsible     TEXT REFERENCES employees(id),
  status          TEXT DEFAULT 'pending',
  last_filed      TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE stock_adjustments (
  id              TEXT PRIMARY KEY,
  adjustment_no   TEXT UNIQUE NOT NULL,
  item_id         TEXT REFERENCES items(id),
  location_id     TEXT REFERENCES store_locations(id),
  batch_no        TEXT,
  quantity_before NUMERIC(15,2) NOT NULL,
  quantity_after  NUMERIC(15,2) NOT NULL,
  variance        NUMERIC(15,2) NOT NULL,
  reason_code     TEXT NOT NULL,
  notes           TEXT,
  requested_by    TEXT REFERENCES employees(id),
  approved_by     TEXT REFERENCES employees(id),
  approved_at     TEXT,
  status          TEXT DEFAULT 'pending',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE stock_balances (
  id            TEXT PRIMARY KEY,
  item_id       TEXT REFERENCES items(id),
  location_id   TEXT REFERENCES store_locations(id),
  batch_no      TEXT,
  quantity      NUMERIC(15,2) NOT NULL DEFAULT 0,
  updated_at    TEXT DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE(item_id, location_id, batch_no)
);

CREATE TABLE stock_batches (
  id              TEXT PRIMARY KEY,
  item_id         TEXT REFERENCES items(id),
  batch_no        TEXT NOT NULL,
  manufacture_date TEXT,
  expiry_date     TEXT,
  grn_id          TEXT REFERENCES grns(id),
  supplier_id     TEXT REFERENCES suppliers(id),
  unit_cost       NUMERIC(15,2),
  status          TEXT DEFAULT 'active',
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE(item_id, batch_no)
);

CREATE TABLE stock_movements (
  id          TEXT PRIMARY KEY,
  item_id     TEXT REFERENCES items(id),
  type        TEXT NOT NULL,
  quantity    NUMERIC(15,2) NOT NULL,
  balance     NUMERIC(15,2) NOT NULL,
  reference   TEXT,
  grn_id      TEXT,
  project_id  TEXT,
  date        TEXT DEFAULT (CURRENT_DATE),
  done_by     TEXT REFERENCES employees(id),
  notes       TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE stock_transfers (
  id              TEXT PRIMARY KEY,
  transfer_no     TEXT UNIQUE NOT NULL,
  item_id         TEXT REFERENCES items(id),
  batch_no        TEXT,
  quantity        NUMERIC(15,2) NOT NULL,
  from_location_id TEXT REFERENCES store_locations(id),
  to_location_id  TEXT REFERENCES store_locations(id),
  status          TEXT DEFAULT 'pending',
  requested_by    TEXT REFERENCES employees(id),
  approved_by     TEXT REFERENCES employees(id),
  approved_at     TEXT,
  completed_at    TEXT,
  notes           TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE store_locations (
  id            TEXT PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  type          TEXT DEFAULT 'warehouse',
  address       TEXT,
  custodian     TEXT REFERENCES employees(id),
  is_active     INTEGER DEFAULT 1,
  created_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE store_requisition_lines (
  id              TEXT PRIMARY KEY,
  requisition_id  TEXT REFERENCES store_requisitions(id),
  item_id         TEXT REFERENCES items(id),
  quantity_requested NUMERIC(15,2) NOT NULL,
  quantity_issued NUMERIC(15,2) DEFAULT 0,
  batch_no        TEXT,
  notes           TEXT
);

CREATE TABLE store_requisitions (
  id              TEXT PRIMARY KEY,
  req_no          TEXT UNIQUE NOT NULL,
  requested_by    TEXT REFERENCES employees(id),
  department      TEXT NOT NULL,
  purpose         TEXT NOT NULL,
  project_id      TEXT REFERENCES projects(id),
  priority        TEXT DEFAULT 'normal',
  status          TEXT DEFAULT 'pending_approval',
  current_approver_role TEXT,
  rejected_by     TEXT REFERENCES employees(id),
  rejected_at     TEXT,
  rejection_reason TEXT,
  closed_at       TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE suppliers (
  id              TEXT PRIMARY KEY,
  code            TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  category        TEXT,
  contact_person  TEXT,
  email           TEXT,
  phone           TEXT,
  address         TEXT,
  kra_pin         TEXT,
  payment_terms   INTEGER DEFAULT 30,
  currency        TEXT DEFAULT 'KES',
  rating          NUMERIC(15,2) DEFAULT 0,
  is_approved     INTEGER DEFAULT 0,
  approved_by     TEXT REFERENCES employees(id),
  approved_at     TEXT,
  bank_name       TEXT,
  bank_account    TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE system_settings (
  key           TEXT PRIMARY KEY,
  value         TEXT,
  category      TEXT DEFAULT 'general',
  description   TEXT,
  updated_by    TEXT REFERENCES employees(id),
  updated_at    TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE tasks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  assignee_id TEXT REFERENCES employees(id),
  due_date    TEXT NOT NULL,
  priority    TEXT DEFAULT 'medium',
  module      TEXT,
  status      TEXT DEFAULT 'pending',
  completed_at TEXT,
  created_by  TEXT REFERENCES employees(id),
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE tax_invoice_lines (
  id              TEXT PRIMARY KEY,
  invoice_id      TEXT REFERENCES tax_invoices(id),
  description     TEXT NOT NULL,
  quantity        NUMERIC(15,2) DEFAULT 1,
  unit_price      NUMERIC(15,2) NOT NULL,
  vat_category    TEXT DEFAULT 'A',
  vat_rate        NUMERIC(15,2) DEFAULT 0.16,
  amount          NUMERIC(15,2) NOT NULL,
  vat_amount      NUMERIC(15,2) DEFAULT 0
, item_id TEXT REFERENCES items(id));

CREATE TABLE tax_invoices (
  id              TEXT PRIMARY KEY,
  invoice_no      TEXT UNIQUE NOT NULL,
  etims_cu_no     TEXT,
  etims_receipt_no TEXT,
  client_id       TEXT REFERENCES clients(id),
  client_pin      TEXT,
  date            TEXT NOT NULL,
  due_date        TEXT,
  subtotal        NUMERIC(15,2) NOT NULL,
  vat_amount      NUMERIC(15,2) DEFAULT 0,
  vat_rate        NUMERIC(15,2) DEFAULT 0.16,
  total           NUMERIC(15,2) NOT NULL,
  status          TEXT DEFAULT 'draft',
  etims_status    TEXT DEFAULT 'pending',
  etims_submitted_at TEXT,
  etims_response  TEXT,
  project_id      TEXT,
  created_by      TEXT REFERENCES employees(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
, company_id TEXT REFERENCES companies(id));

CREATE TABLE trips (
  id              TEXT PRIMARY KEY,
  vehicle_id      TEXT REFERENCES vehicles(id),
  driver_id       TEXT REFERENCES employees(id),
  date            TEXT NOT NULL,
  purpose         TEXT NOT NULL,
  from_location   TEXT,
  to_location     TEXT,
  start_mileage   INTEGER,
  end_mileage     INTEGER,
  distance        INTEGER,
  fuel_litres     NUMERIC(15,2) DEFAULT 0,
  fuel_cost       NUMERIC(15,2) DEFAULT 0,
  project_id      TEXT REFERENCES projects(id),
  client_id       TEXT REFERENCES clients(id),
  is_authorised   INTEGER DEFAULT 0,
  authorised_by   TEXT REFERENCES employees(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE user_roles (
  user_id       TEXT REFERENCES users(id),
  role_id       TEXT REFERENCES roles(id),
  assigned_by   TEXT REFERENCES employees(id),
  assigned_at   TEXT DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE users (
  id          TEXT PRIMARY KEY,
  employee_id TEXT REFERENCES employees(id),
  email       TEXT UNIQUE NOT NULL,
  password    TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'staff',
  mfa_enabled INTEGER DEFAULT 0,
  mfa_secret  TEXT,
  is_active   INTEGER DEFAULT 1,
  last_login  TEXT,
  created_at  TEXT DEFAULT (CURRENT_TIMESTAMP),
  updated_at  TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE vat_returns (
  id              TEXT PRIMARY KEY,
  period          TEXT UNIQUE NOT NULL,
  output_vat      NUMERIC(15,2) DEFAULT 0,
  input_vat       NUMERIC(15,2) DEFAULT 0,
  net_vat         NUMERIC(15,2) DEFAULT 0,
  status          TEXT DEFAULT 'draft',
  filed_at        TEXT,
  payment_ref     TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE vehicle_insurance_history (
  id              TEXT PRIMARY KEY,
  vehicle_id      TEXT REFERENCES vehicles(id),
  insurance_co    TEXT NOT NULL,
  policy_no       TEXT,
  cover_type      TEXT,
  premium         NUMERIC(15,2),
  start_date      TEXT NOT NULL,
  end_date        TEXT NOT NULL,
  doc_path        TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE vehicle_maintenance (
  id              TEXT PRIMARY KEY,
  vehicle_id      TEXT REFERENCES vehicles(id),
  type            TEXT NOT NULL,
  description     TEXT NOT NULL,
  date            TEXT NOT NULL,
  mileage_at_service INTEGER,
  cost            NUMERIC(15,2) DEFAULT 0,
  vendor          TEXT,
  next_due_date   TEXT,
  next_due_mileage INTEGER,
  items_consumed  TEXT,
  performed_by    TEXT REFERENCES employees(id),
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE vehicles (
  id              TEXT PRIMARY KEY,
  reg_no          TEXT UNIQUE NOT NULL,
  make            TEXT,
  model           TEXT,
  year            INTEGER,
  class           TEXT DEFAULT 'C',
  color           TEXT,
  chassis_no      TEXT,
  engine_no       TEXT,
  fuel_type       TEXT DEFAULT 'diesel',
  assigned_driver TEXT REFERENCES employees(id),
  insurance_co    TEXT,
  insurance_policy TEXT,
  insurance_from  TEXT,
  insurance_to    TEXT,
  inspection_to   TEXT,
  service_due     TEXT,
  mileage         INTEGER DEFAULT 0,
  status          TEXT DEFAULT 'active',
  gps_unit_id     TEXT,
  created_at      TEXT DEFAULT (CURRENT_TIMESTAMP)
);

-- ── INDEXES ──────────────────────────────────────────────

CREATE INDEX idx_audit_created ON audit_log(created_at);
CREATE INDEX idx_audit_module ON audit_log(module);
CREATE INDEX idx_audit_user ON audit_log(user_id);
CREATE INDEX idx_bids_stage ON bids(stage);
CREATE INDEX idx_clients_owner ON clients(account_owner);
CREATE INDEX idx_employees_dept ON employees(department);
CREATE INDEX idx_imprest_employee ON imprest(employee_id);
CREATE INDEX idx_imprest_status ON imprest(status);
CREATE INDEX idx_invoices_client ON tax_invoices(client_id);
CREATE INDEX idx_invoices_etims ON tax_invoices(etims_status);
CREATE INDEX idx_items_category ON items(category);
CREATE INDEX idx_projects_status ON projects(status);